// CertificationNation study content — SC-900, batch 1.
// Concepts are the single source for Pocket Notes, recall cards and Field Guide bookmarks.
// Scenarios (Real-World Practice) live in data-cn-sc-scenarios.js and link back by concept id.
// Comparisons shared across certifications live in data-cn-compare.js.
//
// Rules (checked by tools/check-content.js):
//  - ids are permanent. Fix text in place; never renumber or reuse an id.
//  - lines: 3-5 short lines, 60 words or fewer in total. clue: one line. except: only when a
//    shortcut would mislead. more: optional longer explanation, collapsed in the UI.
//  - cards: purpose-written recall prompts. kind "term" (term -> meaning) or "use" (situation -> concept).
//  - obj: CertificationNation's numbering of Microsoft's published SC-900 skills outline
//    (Microsoft does not number the bullets). objTitle carries the outline wording.
//  - status: "source-checked" = checked against the linked Microsoft Learn pages by an automated
//    review pass on the reviewed date. It is NOT a human expert review.
(function(){
const REV="2026-09-30", ML="https://learn.microsoft.com/en-us/";
const O={
  "1.1":"Describe security and compliance concepts",
  "1.2":"Define identity concepts",
  "2.1":"Describe function and identity types of Microsoft Entra ID",
  "2.2":"Describe authentication capabilities of Microsoft Entra ID",
  "2.3":"Describe access management capabilities of Microsoft Entra ID",
  "2.4":"Describe identity protection and governance capabilities of Microsoft Entra",
  "3.1":"Describe core infrastructure security services in Azure",
  "3.2":"Describe security management capabilities of Azure",
  "3.3":"Describe capabilities of Microsoft Sentinel",
  "3.4":"Describe threat protection with Microsoft Defender XDR",
  "4.1":"Describe Microsoft Service Trust Portal and privacy principles",
  "4.2":"Describe compliance management capabilities of Microsoft Purview",
  "4.3":"Describe information protection, data lifecycle management, and data governance capabilities of Microsoft Purview",
  "4.4":"Describe insider risk, eDiscovery, and audit capabilities in Microsoft Purview"
};
const S={
  concepts: ML+"training/modules/describe-security-concepts-methodologies/",
  identity: ML+"training/modules/describe-identity-principles-concepts/",
  sharedResp: ML+"azure/security/fundamentals/shared-responsibility",
  zeroTrust: ML+"security/zero-trust/zero-trust-overview",
  entra: ML+"entra/fundamentals/whatis",
  workload: ML+"entra/workload-id/workload-identities-overview",
  managedId: ML+"entra/identity/managed-identities-azure-resources/overview",
  hybrid: ML+"entra/identity/hybrid/whatis-hybrid-identity",
  external: ML+"entra/external-id/external-identities-overview",
  devices: ML+"entra/identity/devices/overview",
  authMethods: ML+"entra/identity/authentication/concept-authentication-methods",
  mfa: ML+"entra/identity/authentication/concept-mfa-howitworks",
  secDefaults: ML+"entra/fundamentals/security-defaults",
  sspr: ML+"entra/identity/authentication/concept-sspr-howitworks",
  pwProtect: ML+"entra/identity/authentication/concept-password-ban-bad",
  smartLockout: ML+"entra/identity/authentication/howto-password-smart-lockout",
  ca: ML+"entra/identity/conditional-access/overview",
  rbac: ML+"entra/identity/role-based-access-control/custom-overview",
  governance: ML+"entra/id-governance/identity-governance-overview",
  accessReviews: ML+"entra/id-governance/access-reviews-overview",
  entitlement: ML+"entra/id-governance/entitlement-management-overview",
  pim: ML+"entra/id-governance/privileged-identity-management/pim-configure",
  idProtection: ML+"entra/id-protection/overview-identity-protection",
  ddos: ML+"azure/ddos-protection/ddos-protection-overview",
  firewall: ML+"azure/firewall/overview",
  waf: ML+"azure/web-application-firewall/overview",
  vnet: ML+"azure/virtual-network/virtual-networks-overview",
  nsg: ML+"azure/virtual-network/network-security-groups-overview",
  bastion: ML+"azure/bastion/bastion-overview",
  keyVault: ML+"azure/key-vault/general/overview",
  mdc: ML+"azure/defender-for-cloud/defender-for-cloud-introduction",
  cspm: ML+"azure/defender-for-cloud/concept-cloud-security-posture-management",
  secureScore: ML+"azure/defender-for-cloud/secure-score-security-controls",
  sentinel: ML+"azure/sentinel/overview",
  xdr: ML+"defender-xdr/microsoft-365-defender",
  mdo: ML+"defender-office-365/mdo-about",
  mde: ML+"defender-endpoint/microsoft-defender-endpoint",
  mdca: ML+"defender-cloud-apps/what-is-defender-for-cloud-apps",
  mdi: ML+"defender-for-identity/what-is",
  mdvm: ML+"defender-vulnerability-management/defender-vulnerability-management",
  mdti: ML+"defender/threat-intelligence/what-is-microsoft-defender-threat-intelligence-defender-ti",
  stp: ML+"purview/get-started-with-service-trust-portal",
  privacy: "https://privacy.microsoft.com/en-us/privacystatement",
  compMgr: ML+"purview/compliance-manager",
  purview: ML+"purview/purview-portal",
  compScore: ML+"purview/compliance-manager-scoring",
  classification: ML+"purview/data-classification-overview",
  sits: ML+"purview/sit-sensitive-information-type-learn-about",
  labels: ML+"purview/sensitivity-labels",
  dlp: ML+"purview/dlp-learn-about-dlp",
  retention: ML+"purview/retention",
  records: ML+"purview/records-management",
  irm: ML+"purview/insider-risk-management",
  ediscovery: ML+"purview/edisc",
  audit: ML+"purview/audit-solutions-overview",
  studyGuide: ML+"credentials/certifications/resources/study-guides/sc-900"
};
const C=(id,day,dom,obj,topic,title,lines,clue,cards,src,extra)=>Object.assign(
  {id:"sc."+id,cert:"sc",day,dom,obj,objTitle:O[obj],topic,title,lines,clue,cards:cards.map((c,i)=>({id:"sc."+id+".c"+(i+1),kind:c[0],q:c[1],a:c[2]})),
   src:src.map(k=>S[k]||k),reviewed:REV,status:"source-checked",v:1},extra||{});

const concepts=[
// ---- Level 1 · 1.1 security and compliance concepts
C("cia",1,"Concepts","1.1","Security basics","The CIA triad",
  ["Confidentiality: only the right people can read it.","Integrity: nobody changed it without permission.","Availability: it's there when it's needed.","Most security controls protect at least one of the three."],
  "Name the harm first (exposed, altered, unreachable), then pick the control.",
  [["term","What does integrity protect in the CIA triad?","That data hasn't been changed without authorization."],
   ["use","A flood of traffic takes the clinic's booking site offline. Which part of CIA is hit?","Availability."]],
  ["concepts"]),
C("shared-resp",1,"Concepts","1.1","Security basics","Shared responsibility model",
  ["The cloud provider always owns the physical datacenter, network and hosts.","You always own your data, devices, and accounts and identities.","Everything in between shifts with the model.","IaaS leaves you the most work, PaaS less, SaaS the least."],
  "Whatever the model, protecting your data and accounts stays with you.",
  [["term","In every cloud model, which three things stay the customer's responsibility?","Information and data, devices, and accounts and identities."],
   ["use","A team moves from VMs they patch themselves to a SaaS app. Does their share of the work grow or shrink?","It shrinks: SaaS leaves the customer the least to manage."]],
  ["sharedResp"]),
C("defense-in-depth",1,"Concepts","1.1","Security basics","Defense in depth",
  ["Several layers of protection, so one failure isn't a breach.","Each layer slows an attacker and buys time to detect them.","Microsoft's layers: physical, identity and access, perimeter, network, compute, application, data."],
  "Layers that back each other up, not one strong wall.",
  [["term","What is the goal of defense in depth?","Layered controls, so if one fails the next still slows or stops the attacker."],
   ["use","A school adds MFA even though it already has a firewall, because a stolen password could get past the firewall. Which strategy is this?","Defense in depth."]],
  ["concepts"]),
C("zero-trust",1,"Concepts","1.1","Security basics","Zero Trust",
  ["Don't trust a request just because it comes from inside the network.","Verify explicitly: check identity, device, location and risk every time.","Use least-privilege access.","Assume breach: segment, encrypt, and watch for attackers already inside."],
  "Being on the network is never proof of trust.",
  [["term","What are Zero Trust's three guiding principles?","Verify explicitly, use least-privilege access, assume breach."],
   ["use","A hospital limits each app so a compromised account can reach only one segment. Which Zero Trust principle drives that?","Assume breach (limit the blast radius)."]],
  ["zeroTrust"],{more:"Microsoft applies Zero Trust across six areas: identities, devices, applications, data, infrastructure and networks. It is a strategy, not a single product."}),
C("encryption",2,"Concepts","1.1","Security basics","Encryption",
  ["Scrambles data so only someone with the key can read it.","Symmetric: one shared key encrypts and decrypts. Fast.","Asymmetric: a public key encrypts; only the matching private key decrypts.","Protect data at rest (stored) and in transit (moving)."],
  "Encryption is reversible with the right key.",
  [["term","In asymmetric encryption, which key decrypts data encrypted with a public key?","The matching private key."],
   ["use","Laptops leave the office with customer files on the disk. Which state of data does disk encryption protect?","Data at rest."]],
  ["concepts"]),
C("hashing",2,"Concepts","1.1","Security basics","Hashing",
  ["A one-way function: same input, same fixed-length output.","You can't reverse a hash back to the original data.","Used to store passwords and to prove a file hasn't changed.","Salting adds random data first, so identical passwords get different hashes."],
  "If the question needs the original back, it isn't hashing.",
  [["term","Why add a salt before hashing a password?","So identical passwords produce different hashes, which defeats precomputed lookup tables."],
   ["use","An admin compares a downloaded installer's value with the vendor's published value to confirm nothing changed. What is being compared?","Hashes."]],
  ["concepts"]),
C("grc",2,"Concepts","1.1","Security basics","Governance, risk and compliance (GRC)",
  ["Governance: the rules, policies and processes your organization sets.","Risk: finding, assessing and responding to threats to the business.","Compliance: meeting outside laws, regulations and standards.","Data residency, sovereignty and privacy are common compliance topics."],
  "Internal rules are governance; outside rules are compliance.",
  [["term","In GRC, what does compliance mean?","Following external laws, regulations and standards."],
   ["use","A company writes its own policy that all laptops must be encrypted. Which part of GRC is that?","Governance."]],
  ["concepts"]),
// ---- Level 2 · 1.2 identity concepts
C("identity-perimeter",2,"Concepts","1.2","Identity concepts","Identity as the primary security perimeter",
  ["People and apps connect from anywhere, so the network edge no longer contains everything.","Identity is now the control point for access.","Four identity pillars: administration, authentication, authorization, auditing."],
  "Remote work and cloud apps are the reason identity replaced the network edge.",
  [["term","Why is identity called the primary security perimeter?","Users and resources sit outside the corporate network, so access decisions hang on who is asking, not where they are."],
   ["term","Name the four pillars of an identity infrastructure.","Administration, authentication, authorization, auditing."]],
  ["identity"]),
C("authn",2,"Concepts","1.2","Identity concepts","Authentication (AuthN)",
  ["Proves you are who you claim to be.","Uses credentials: something you know, have, or are.","Always comes before authorization."],
  "\"Prove it's you\" wording points to authentication.",
  [["term","What question does authentication answer?","Are you who you say you are?"],
   ["use","A nurse scans a badge and enters a PIN at a shared workstation. Which process is happening?","Authentication."]],
  ["identity"]),
C("authz",2,"Concepts","1.2","Identity concepts","Authorization (AuthZ)",
  ["Decides what an authenticated identity can do.","Permissions, roles and access levels live here.","Happens after authentication."],
  "\"Allowed to\" or \"level of access\" wording points to authorization.",
  [["term","What question does authorization answer?","What are you allowed to do?"],
   ["use","A signed-in intern can read the shared drive but not delete files. Which process set that limit?","Authorization."]],
  ["identity"]),
C("idp",2,"Concepts","1.2","Identity concepts","Identity providers and SSO",
  ["An identity provider (IdP) signs users in and issues tokens to apps.","Apps trust the token instead of storing passwords.","Single sign-on (SSO): sign in once, reach many apps.","Microsoft Entra ID is an identity provider."],
  "Modern authentication: apps rely on a trusted IdP's token.",
  [["term","What does an identity provider do?","Authenticates users and issues security tokens that apps trust."],
   ["use","Staff sign in once each morning and open email, HR and payroll without another prompt. What is this?","Single sign-on (SSO)."]],
  ["identity"]),
C("directory",2,"Concepts","1.2","Identity concepts","Directory services and Active Directory",
  ["A directory stores information about users, groups and devices.","Active Directory Domain Services (AD DS) is the classic on-premises directory.","Microsoft Entra ID is a cloud identity service, not AD DS hosted in the cloud."],
  "On-prem domain controllers point to AD DS.",
  [["term","What is Active Directory Domain Services (AD DS)?","Microsoft's traditional on-premises directory service, run on domain controllers."],
   ["term","Is Microsoft Entra ID simply AD DS running in the cloud?","No. It is a separate cloud identity service with different capabilities."]],
  ["identity"]),
C("federation",2,"Concepts","1.2","Identity concepts","Federation",
  ["A trust between separate identity providers.","Users sign in with their home credentials and reach the other side's resources.","Neither side stores the other's passwords.","Trust can be one-way; it doesn't have to run both ways."],
  "Two organizations, two identity providers, one trust.",
  [["term","What is federation?","A trust relationship that lets one identity provider's users access resources relying on another."],
   ["use","A university lets staff from a partner hospital use their hospital sign-in to reach a shared research portal. What makes that possible?","Federation."]],
  ["identity"]),
// ---- Level 3 · 2.1 Entra ID and identity types
C("entra-id",3,"Entra","2.1","Microsoft Entra ID","Microsoft Entra ID and tenants",
  ["Microsoft's cloud identity and access management service.","Formerly called Azure Active Directory (Azure AD).","A tenant is your organization's dedicated instance of it.","Used by Microsoft 365, Azure, and thousands of other apps."],
  "Older material says Azure AD; exam wording says Entra ID.",
  [["term","What is a Microsoft Entra tenant?","An organization's dedicated instance of Microsoft Entra ID."],
   ["term","What was Microsoft Entra ID called before?","Azure Active Directory (Azure AD)."]],
  ["entra"]),
C("identity-types",3,"Entra","2.1","Microsoft Entra ID","Users, guests and groups",
  ["Member users belong to your organization.","Guest users come from outside, such as partners.","Security groups grant access to resources.","Microsoft 365 groups add shared collaboration (mailbox, files, calendar)."],
  "Access control points to a security group; collaboration points to a Microsoft 365 group.",
  [["term","What is a guest user in Microsoft Entra ID?","An external person invited into your tenant, usually signing in with their own account."],
   ["use","A project team needs a shared inbox, calendar and file library. Which group type fits?","A Microsoft 365 group."]],
  ["entra"]),
C("workload-identity",3,"Entra","2.1","Microsoft Entra ID","Workload identities",
  ["Identities for software, not people.","Service principal: an app's identity in a tenant.","Managed identity: Azure manages the credential, so no secret sits in code.","System-assigned lives with one resource; user-assigned can be shared."],
  "\"Without storing credentials in code\" points to a managed identity.",
  [["term","What is a managed identity?","A workload identity whose credentials Azure manages automatically for an Azure resource."],
   ["term","How does a system-assigned managed identity differ from a user-assigned one?","System-assigned is tied to one resource and deleted with it; user-assigned is standalone and reusable."]],
  ["workload","managedId"]),
C("hybrid-identity",3,"Entra","2.1","Microsoft Entra ID","Hybrid identity",
  ["Connects on-premises Active Directory with Microsoft Entra ID.","Users get one identity for on-prem and cloud apps.","Microsoft Entra Connect Sync or Cloud Sync keeps accounts in sync."],
  "\"Keep using on-prem AD accounts in the cloud\" points to Entra Connect.",
  [["term","What tool synchronizes on-premises AD accounts to Microsoft Entra ID?","Microsoft Entra Connect (Connect Sync or Cloud Sync)."],
   ["use","A school district wants staff to use their existing domain account for Microsoft 365. What does it need?","Hybrid identity, synchronizing AD with Entra ID."]],
  ["hybrid"],{more:"Sign-in can use password hash synchronization, pass-through authentication, or federation. Cloud Sync uses lightweight agents; Connect Sync runs on a server you manage."}),
C("external-identities",3,"Entra","2.1","Microsoft Entra ID","External identities (B2B)",
  ["Microsoft Entra External ID covers people outside your organization.","B2B collaboration invites partners as guests who sign in with their own accounts.","You control what guests can reach; they manage their own credentials.","External ID also supports customer-facing apps."],
  "Partner using their own work email points to B2B collaboration.",
  [["term","What does B2B collaboration let you do?","Invite external users as guests who sign in with their own work, school or personal accounts."],
   ["use","A vendor's staff need access to one SharePoint site, and you don't want to manage their passwords. What fits?","B2B collaboration (guest access)."]],
  ["external"]),
C("device-identity",3,"Entra","2.1","Microsoft Entra ID","Device identities",
  ["Registered: usually personal (BYOD) or mobile devices.","Joined: usually organization-owned, signing in with an Entra account.","Hybrid joined: joined to on-prem AD and registered in Entra ID."],
  "Ownership is a hint, but the answer is how the device is joined.",
  [["term","What is a Microsoft Entra hybrid joined device?","A device joined to on-premises AD that is also registered in Microsoft Entra ID."],
   ["use","Employees add a work account to their personal phones to reach email. Which device state is this, typically?","Microsoft Entra registered."]],
  ["devices"],{except:"\"Typically\" matters: an organization can register a device it owns, so read the join method, not just who paid for it."}),
// ---- Level 4 · 2.2 authentication
C("auth-methods",4,"Entra","2.2","Authentication","Passwordless authentication methods",
  ["Windows Hello for Business: PIN or biometric tied to the device.","Microsoft Authenticator phone sign-in.","FIDO2 security keys and passkeys.","Certificate-based authentication.","SMS and voice calls work, but are the weakest methods."],
  "Phishing-resistant options: Windows Hello for Business, FIDO2 keys and passkeys, certificates.",
  [["term","Name two passwordless methods in Microsoft Entra ID.","Any two of: Windows Hello for Business, Authenticator phone sign-in, FIDO2 security keys/passkeys, certificate-based authentication."],
   ["use","A lab uses shared workstations and wants phishing-resistant sign-in with a physical key. What fits?","FIDO2 security keys."]],
  ["authMethods"]),
C("mfa",4,"Entra","2.2","Authentication","Multifactor authentication (MFA)",
  ["Requires two or more different types of factor.","Something you know: password or PIN.","Something you have: phone or security key.","Something you are: fingerprint or face."],
  "Two passwords are still one factor type.",
  [["term","What makes authentication \"multifactor\"?","Using two or more different factor types: know, have, are."],
   ["use","A sign-in asks for a password and a security question. Is that MFA?","No. Both are something you know."]],
  ["mfa"]),
C("security-defaults",4,"Entra","2.2","Authentication","Security defaults",
  ["A free, preconfigured baseline for Microsoft Entra ID.","Requires users to register for MFA and prompts when needed.","Blocks legacy authentication protocols.","One setting for the whole tenant; no custom rules."],
  "\"No premium licenses\" plus \"basic protection\" points to security defaults.",
  [["term","What do security defaults provide?","A free, tenant-wide baseline: MFA registration and prompts, plus blocking legacy authentication."],
   ["use","A 12-person nonprofit with free licensing wants basic MFA protection fast. What should it turn on?","Security defaults."]],
  ["secDefaults"],{except:"Security defaults and Conditional Access policies don't run together; turning on custom policies means turning security defaults off."}),
C("sspr",4,"Entra","2.2","Authentication","Self-service password reset (SSPR)",
  ["Users reset their own password after verifying with registered methods.","Methods include the Authenticator app, a phone number, or email.","Cuts help desk calls for forgotten passwords.","Password writeback can update on-premises AD too."],
  "\"Users reset their own password\" points to SSPR.",
  [["term","What does SSPR let users do?","Reset or unlock their own account after verifying their identity, without the help desk."],
   ["use","A help desk spends Monday mornings resetting forgotten passwords. Which Entra feature cuts that work?","Self-service password reset (SSPR)."]],
  ["sspr"]),
C("password-protection",4,"Entra","2.2","Authentication","Password protection and smart lockout",
  ["A global banned password list blocks common weak passwords.","A custom banned list adds your own terms, such as the company name.","Smart lockout locks out attackers while letting the real user in.","Can extend to on-premises AD."],
  "\"Block passwords containing our company name\" points to the custom banned list.",
  [["term","What does smart lockout do?","Locks out sign-in attempts that look like an attacker while trying to keep the genuine user signed in."],
   ["use","Staff keep choosing passwords like \"Riverside1!\" built on the company name. Which feature stops that?","Password protection with a custom banned password list."]],
  ["pwProtect","smartLockout"],{more:"The custom banned password list requires Microsoft Entra ID P1 or P2."}),
// ---- Level 5 · 2.3 access management
C("conditional-access",5,"Entra","2.3","Access management","Conditional Access",
  ["If-then policies that decide access at sign-in.","Signals: user, location, device, app, and sign-in risk.","Decisions: block, grant, or grant with conditions like MFA or a compliant device.","Requires Microsoft Entra ID P1."],
  "\"Only if\" or \"except when\" access rules point to Conditional Access.",
  [["term","What three kinds of decision can a Conditional Access policy make?","Block access, grant access, or grant access only when conditions like MFA or a compliant device are met."],
   ["use","Finance wants MFA required only when staff sign in from outside the office network. What fits?","A Conditional Access policy using location as a signal."]],
  ["ca"],{more:"Report-only mode shows what a policy would do before you enforce it. Risk-based signals come from Microsoft Entra ID Protection."}),
C("entra-rbac",5,"Entra","2.3","Access management","Microsoft Entra roles and RBAC",
  ["Role-based access control assigns permissions through roles.","Built-in roles cover common admin jobs, such as User Administrator.","Custom roles let you pick exact permissions.","Give the narrowest role that does the job."],
  "Least privilege: avoid Global Administrator unless the task truly needs it.",
  [["term","What principle should guide which Entra role you assign?","Least privilege: the narrowest role that covers the task."],
   ["use","A help desk tech only needs to reset users' passwords. Global Administrator or a narrower built-in role?","A narrower built-in role scoped to that task."]],
  ["rbac"],{except:"Microsoft Entra roles manage Entra objects such as users and groups; Azure RBAC roles manage Azure resources such as VMs. They're separate systems."}),
// ---- Level 5 · 2.4 protection and governance
C("id-governance",5,"Entra","2.4","Protection and governance","Microsoft Entra ID Governance",
  ["Manages the identity lifecycle: joiners, movers, leavers.","Entitlement management bundles access into access packages with approval and expiry.","Access reviews and PIM are part of the governance toolkit.","Goal: the right people keep the right access for the right time."],
  "\"Access that expires\" or \"request access to a bundle\" points to entitlement management.",
  [["term","What is an access package in entitlement management?","A bundle of groups, apps and sites a user can request, often with approval and an expiry date."],
   ["use","A new hire should get the same set of apps as their team, then lose them when they leave. Which capability covers that?","Microsoft Entra ID Governance (identity lifecycle and entitlement management)."]],
  ["governance","entitlement"]),
C("access-reviews",5,"Entra","2.4","Protection and governance","Access reviews",
  ["Reviewers confirm who still needs access to groups, apps or roles.","Can run on a schedule, such as every quarter.","Unanswered or denied access can be removed automatically."],
  "\"Periodically confirm who still needs access\" points to access reviews.",
  [["term","What is an access review?","A recurring check where reviewers confirm or remove people's access to groups, apps or roles."],
   ["use","Auditors ask the clinic to prove managers re-approve access to the billing app every quarter. What fits?","A recurring access review."]],
  ["accessReviews"]),
C("pim",5,"Entra","2.4","Protection and governance","Privileged Identity Management (PIM)",
  ["Just-in-time access to privileged roles.","Admins are eligible, then activate the role only when needed.","Activation can require MFA, approval and a justification.","Time-limited, and every activation is audited."],
  "\"Just-in-time\" or \"time-bound admin rights\" points to PIM.",
  [["term","What does \"eligible\" mean in PIM?","The user can activate the role when needed, but doesn't hold it permanently."],
   ["use","Admins should hold Global Administrator only for a two-hour window, with approval. What fits?","Privileged Identity Management (PIM)."]],
  ["pim"]),
C("id-protection",5,"Entra","2.4","Protection and governance","Microsoft Entra ID Protection",
  ["Detects identity-based risk in the cloud.","Sign-in risk: anonymous IP, atypical travel, unfamiliar sign-in properties.","User risk: signs an account is compromised, such as leaked credentials.","Risk levels can drive Conditional Access."],
  "Risky cloud sign-ins point to ID Protection, not Defender for Identity.",
  [["term","What is the difference between sign-in risk and user risk?","Sign-in risk: this sign-in probably isn't the owner. User risk: the account itself is probably compromised."],
   ["use","A user's credentials show up in a public leak. Which Entra feature flags the account?","Microsoft Entra ID Protection (user risk: leaked credentials)."]],
  ["idProtection"]),
// ---- Level 7 · 3.1 infrastructure security
C("ddos",7,"Security solutions","3.1","Azure infrastructure","Azure DDoS Protection",
  ["Defends Azure resources against distributed denial-of-service attacks.","Tuned to your application's normal traffic patterns.","Protects availability, not confidentiality."],
  "Floods of traffic meant to knock a service offline point to DDoS Protection.",
  [["term","Which part of the CIA triad does Azure DDoS Protection protect?","Availability."],
   ["use","A school's public website keeps going down under massive junk traffic. Which Azure service addresses that?","Azure DDoS Protection."]],
  ["ddos"]),
C("azure-firewall",7,"Security solutions","3.1","Azure infrastructure","Azure Firewall",
  ["A managed, cloud-native, stateful firewall service.","Filters by FQDN and application rules, not just IP and port.","Can use Microsoft threat intelligence to block known-bad addresses.","One central policy across many virtual networks."],
  "\"Stateful\" alone doesn't separate it from an NSG; FQDN filtering and central policy do.",
  [["term","What can Azure Firewall do that a network security group can't?","Filter by FQDN and application rules, use threat intelligence, and apply one policy centrally across networks."],
   ["use","Servers in several VNets may reach only *.windowsupdate.com on the internet. What fits?","Azure Firewall with application/FQDN rules."]],
  ["firewall"]),
C("waf",7,"Security solutions","3.1","Azure infrastructure","Web Application Firewall (WAF)",
  ["Protects web apps from common exploits.","Examples: SQL injection and cross-site scripting.","Runs on Application Gateway or Azure Front Door."],
  "Attacks inside web requests point to WAF.",
  [["term","Which two web attacks is WAF best known for blocking?","SQL injection and cross-site scripting (XSS)."],
   ["use","A patient portal is being probed with SQL injection strings. Which Azure service inspects that traffic?","Azure Web Application Firewall (WAF)."]],
  ["waf"]),
C("vnet-segmentation",7,"Security solutions","3.1","Azure infrastructure","Network segmentation with virtual networks",
  ["A virtual network (VNet) is isolated by default.","Subnets split a VNet into smaller segments.","NSGs and firewalls control traffic between segments.","Peering connects VNets when you choose to."],
  "Segmentation limits how far an attacker can move.",
  [["term","Are Azure virtual networks connected to each other by default?","No. VNets are isolated unless you connect them, for example with peering."],
   ["use","A team puts web servers and databases in different subnets with rules between them. What is this?","Network segmentation."]],
  ["vnet"]),
C("nsg",7,"Security solutions","3.1","Azure infrastructure","Network security groups (NSGs)",
  ["Allow or deny rules by source, destination, port and protocol.","Attached to a subnet or a network interface.","Rules are evaluated by priority number, lowest first."],
  "Simple IP and port rules on a subnet or NIC point to an NSG.",
  [["term","What does an NSG filter on?","Source and destination, port and protocol."],
   ["use","Only the app subnet should reach the database subnet on port 1433. What's the simplest control?","A network security group rule."]],
  ["nsg"]),
C("bastion",7,"Security solutions","3.1","Azure infrastructure","Azure Bastion",
  ["RDP and SSH to VMs through the Azure portal over TLS.","The VMs don't need public IP addresses.","Removes the need to expose management ports to the internet."],
  "Remote admin access without public IPs points to Bastion.",
  [["term","Why use Azure Bastion?","Secure RDP/SSH to VMs over TLS without giving the VMs public IP addresses."],
   ["use","Auditors flag that VMs expose port 3389 to the internet. Which service lets admins still connect?","Azure Bastion."]],
  ["bastion"]),
C("key-vault",7,"Security solutions","3.1","Azure infrastructure","Azure Key Vault",
  ["Central, secure storage for secrets, keys and certificates.","Apps fetch secrets at run time instead of hard-coding them.","Access is controlled and logged."],
  "Secrets, keys or certificates to store point to Key Vault.",
  [["term","What three kinds of item does Azure Key Vault store?","Secrets, keys and certificates."],
   ["use","A connection string is sitting in a public code repo. Where should it live instead?","Azure Key Vault."]],
  ["keyVault"]),
// ---- Level 7 · 3.2 security management
C("defender-for-cloud",7,"Security solutions","3.2","Azure security management","Microsoft Defender for Cloud",
  ["A cloud-native application protection platform (CNAPP).","Posture management finds misconfigurations (CSPM).","Workload protection guards servers, containers, storage and databases.","Covers Azure, AWS, Google Cloud and on-premises machines."],
  "Cloud posture plus workload protection across clouds points to Defender for Cloud.",
  [["term","What are Defender for Cloud's two main halves?","Cloud security posture management (CSPM) and cloud workload protection (Defender plans)."],
   ["use","A company runs workloads in Azure and AWS and wants one place to see misconfigurations. What fits?","Microsoft Defender for Cloud."]],
  ["mdc"]),
C("cspm",7,"Security solutions","3.2","Azure security management","Cloud security posture management and Secure Score",
  ["CSPM continuously checks resources against security standards.","Recommendations tell you what to fix.","Secure Score sums up your posture; fixing recommendations raises it.","The default standard is the Microsoft cloud security benchmark."],
  "Secure Score measures security posture, not regulatory compliance.",
  [["term","What raises your Secure Score in Defender for Cloud?","Remediating its security recommendations."],
   ["term","What is the default security standard in Defender for Cloud?","The Microsoft cloud security benchmark (MCSB)."]],
  ["cspm","secureScore"]),
C("cwp",7,"Security solutions","3.2","Azure security management","Cloud workload protection (Defender plans)",
  ["Paid Defender plans add threat protection per workload type.","Examples: servers, containers, storage, databases, App Service.","Raises security alerts when attacks are detected."],
  "Detecting attacks on a workload, not just misconfigurations, points to workload protection.",
  [["term","What do Defender for Cloud's workload protection plans add?","Threat detection and alerts for specific workloads such as servers, storage and databases."],
   ["use","The team wants alerts when malware is uploaded to a storage account. Posture recommendation or workload protection?","Workload protection (a Defender plan)."]],
  ["mdc"]),
// ---- Level 8 · 3.3 Sentinel
C("siem-soar",8,"Security solutions","3.3","Microsoft Sentinel","SIEM and SOAR",
  ["SIEM collects and correlates logs from many sources to detect threats.","SOAR automates the response.","SIEM spots the attack; SOAR acts on it."],
  "Collecting and analyzing logs is SIEM; automated response is SOAR.",
  [["term","What does SOAR add to a SIEM?","Orchestration and automated response, such as playbooks that act on alerts."],
   ["use","Every phishing alert should automatically disable the user and open a ticket. SIEM or SOAR capability?","SOAR."]],
  ["sentinel"]),
C("sentinel",8,"Security solutions","3.3","Microsoft Sentinel","Microsoft Sentinel",
  ["Microsoft's cloud-native SIEM and SOAR.","Collect with data connectors; detect with analytics rules.","Investigate incidents; respond with playbooks.","Workbooks visualize data; hunting uses KQL queries."],
  "Playbooks are Sentinel's automation, built on Azure Logic Apps.",
  [["term","In Microsoft Sentinel, what brings data in?","Data connectors."],
   ["use","An analyst wants to search the last 90 days of logs for signs of an attacker nobody has alerted on yet. What is this called in Sentinel?","Threat hunting (with KQL queries)."]],
  ["sentinel"]),
// ---- Level 8 · 3.4 Defender XDR
C("defender-xdr",8,"Security solutions","3.4","Microsoft Defender XDR","Microsoft Defender XDR and the Defender portal",
  ["Extended detection and response across endpoints, email, identities and apps.","Correlates related alerts into a single incident.","Managed in the Microsoft Defender portal.","Can automatically investigate and remediate."],
  "\"One incident across email, device and identity\" points to Defender XDR.",
  [["term","What does Microsoft Defender XDR do with related alerts?","Groups them into one incident so the whole attack is seen together."],
   ["use","A phishing email, a malware launch on a laptop and a suspicious sign-in all belong to one attack. Where are they correlated?","Microsoft Defender XDR, in the Defender portal."]],
  ["xdr"]),
C("mdo",8,"Security solutions","3.4","Microsoft Defender XDR","Microsoft Defender for Office 365",
  ["Protects email and collaboration tools.","Safe Links checks URLs when clicked.","Safe Attachments opens files in a sandbox before delivery.","Anti-phishing protection and attack simulation training."],
  "Phishing, malicious links or attachments point to Defender for Office 365.",
  [["term","What does Safe Attachments do?","Detonates attachments in a sandbox to check for malware before users get them."],
   ["use","Users keep clicking links in emails that turn malicious hours after delivery. Which feature checks the link at click time?","Safe Links in Defender for Office 365."]],
  ["mdo"]),
C("mde",8,"Security solutions","3.4","Microsoft Defender XDR","Microsoft Defender for Endpoint",
  ["Protects devices: laptops, desktops, servers and mobile.","Endpoint detection and response (EDR) spots attacker behavior.","Attack surface reduction limits what attackers can abuse.","Can isolate a compromised device."],
  "Devices point to Defender for Endpoint.",
  [["term","What does EDR in Defender for Endpoint do?","Detects and investigates suspicious behavior on devices so you can respond."],
   ["use","A laptop shows ransomware behavior and must be cut off from the network while staying manageable. Which product?","Microsoft Defender for Endpoint (device isolation)."]],
  ["mde"]),
C("mdca",8,"Security solutions","3.4","Microsoft Defender XDR","Microsoft Defender for Cloud Apps",
  ["A cloud access security broker (CASB) for SaaS apps.","Discovers shadow IT: cloud apps used without approval.","Controls and monitors data and activity inside cloud apps."],
  "Shadow IT or SaaS app control points to Defender for Cloud Apps.",
  [["term","What kind of product is Microsoft Defender for Cloud Apps?","A cloud access security broker (CASB)."],
   ["use","IT suspects staff are uploading files to unapproved file-sharing sites. Which product discovers that?","Microsoft Defender for Cloud Apps (shadow IT discovery)."]],
  ["mdca"]),
C("mdi",8,"Security solutions","3.4","Microsoft Defender XDR","Microsoft Defender for Identity",
  ["Protects on-premises Active Directory identities.","Sensors run on domain controllers and other identity servers.","Detects attacks like pass-the-hash, reconnaissance and lateral movement."],
  "On-prem AD attacks point to Defender for Identity.",
  [["term","Where are Defender for Identity sensors installed?","On domain controllers and other on-premises identity servers such as AD FS."],
   ["use","Someone is running pass-the-hash attacks against the on-prem domain. Which product detects this?","Microsoft Defender for Identity."]],
  ["mdi"],{except:"Despite the name, it doesn't score cloud sign-in risk; that's Microsoft Entra ID Protection."}),
C("mdvm",8,"Security solutions","3.4","Microsoft Defender XDR","Microsoft Defender Vulnerability Management",
  ["Continuously finds vulnerabilities and misconfigurations on devices.","Prioritizes by risk, so the most dangerous gaps get fixed first.","Tracks remediation work."],
  "\"Which weaknesses should we patch first\" points to vulnerability management.",
  [["term","What does Defender Vulnerability Management prioritize?","Vulnerabilities by actual risk to the organization, so the most dangerous ones are fixed first."],
   ["use","A small IT team can't patch everything this month and needs a ranked list. Which product helps?","Microsoft Defender Vulnerability Management."]],
  ["mdvm"]),
C("threat-intel",8,"Security solutions","3.4","Microsoft Defender XDR","Microsoft Threat Intelligence",
  ["Microsoft's research on threat actors, campaigns and indicators.","Threat analytics reports explain active threats.","Adds context to alerts: who, how, and what to check."],
  "Context about attackers and indicators points to threat intelligence.",
  [["term","What does threat intelligence add to an investigation?","Context about the threat actor, their techniques and related indicators."],
   ["use","An analyst wants to know which known group uses the tools seen in an incident. Where do they look?","Microsoft Threat Intelligence (threat analytics in the Defender portal)."]],
  ["mdti","xdr"]),
// ---- Level 9 · 4.1 trust and privacy
C("stp",9,"Compliance","4.1","Trust and privacy","Service Trust Portal",
  ["Microsoft's public library of audit reports and compliance documents.","Shows how Microsoft secures and runs its own cloud.","Examples: ISO and SOC reports.","Some documents require signing in."],
  "\"Show me Microsoft's audit reports\" points to the Service Trust Portal.",
  [["term","What would you find in the Service Trust Portal?","Microsoft's audit reports and compliance documents, such as ISO and SOC reports."],
   ["use","A hospital's vendor-risk team needs Microsoft's SOC 2 report. Where do they get it?","The Service Trust Portal."]],
  ["stp"]),
C("privacy-principles",9,"Compliance","4.1","Trust and privacy","Microsoft's privacy principles",
  ["Control: you control your data.","Transparency: Microsoft is clear about what it collects and why.","Security, strong legal protections, and no content-based targeting.","Benefits to you: data use benefits the customer."],
  "There are six principles; \"no content-based targeting\" is the one people forget.",
  [["term","Name Microsoft's six privacy principles.","Control, transparency, security, strong legal protections, no content-based targeting, benefits to you."],
   ["term","What does \"no content-based targeting\" promise?","Microsoft won't use your email, chat or files to target advertising."]],
  ["privacy"]),
// ---- Level 9 · 4.2 compliance management
C("compliance-manager",9,"Compliance","4.2","Compliance management","Compliance Manager and compliance score",
  ["Compliance Manager tracks progress against regulations and standards.","Assessments group controls for one regulation.","Improvement actions are your to-do list.","Compliance score measures progress; it doesn't prove compliance."],
  "Regulatory progress points to compliance score, not Secure Score.",
  [["term","What are improvement actions in Compliance Manager?","Recommended steps you take to meet the controls in an assessment."],
   ["term","Does a high compliance score guarantee you're compliant?","No. It measures progress on improvement actions, not legal compliance."]],
  ["compMgr","compScore"],{more:"Controls are Microsoft-managed, customer-managed, or shared. Compliance Manager is in the Microsoft Purview portal."}),
C("purview-portal",9,"Compliance","4.2","Compliance management","Microsoft Purview portal",
  ["The web portal for Microsoft Purview data security, governance and compliance solutions.","Compliance Manager, DLP, labels, retention, eDiscovery and audit are all reached from it.","Access to each solution depends on the admin role you hold."],
  "Purview is the compliance and data-governance family; Defender is the security family.",
  [["term","What is the Microsoft Purview portal?","The central web portal for Microsoft Purview's compliance, data security and governance solutions."],
   ["use","A compliance officer needs one place to reach Compliance Manager, DLP and eDiscovery. Where do they go?","The Microsoft Purview portal."]],
  ["purview"]),
// ---- Level 9 · 4.3 information protection
C("data-classification",9,"Compliance","4.3","Information protection","Data classification",
  ["Sensitive information types match patterns like card or ID numbers.","Trainable classifiers recognize kinds of documents with no fixed pattern.","Content explorer shows where sensitive items are stored.","Activity explorer shows what people do with labeled content."],
  "Pattern points to a sensitive info type; document kind points to a trainable classifier.",
  [["term","When would you use a trainable classifier instead of a sensitive information type?","When the content has no fixed pattern, such as résumés or contracts."],
   ["term","What's the difference between content explorer and activity explorer?","Content explorer shows where sensitive items are; activity explorer shows what's being done with them."]],
  ["classification","sits"]),
C("sensitivity-labels",9,"Compliance","4.3","Information protection","Sensitivity labels",
  ["Classify content, such as Public, General or Confidential.","Can add encryption, watermarks, headers and footers.","Protection travels with the file.","Published to users with label policies; can be applied automatically."],
  "Classify and protect the file itself points to a sensitivity label.",
  [["term","How do sensitivity labels reach users?","Through sensitivity label policies that publish them to users and groups."],
   ["use","A board report must stay encrypted even after it's emailed outside the company. What fits?","A sensitivity label with encryption."]],
  ["labels"]),
C("dlp",9,"Compliance","4.3","Information protection","Data loss prevention (DLP)",
  ["Policies detect sensitive information and warn or block sharing.","Covers Exchange, SharePoint, OneDrive, Teams and devices.","Policy tips coach users in the moment."],
  "Stopping sensitive data from leaving points to DLP.",
  [["term","What is a DLP policy tip?","An in-the-moment notice that tells users their action may break a data policy."],
   ["use","Staff should be warned before emailing a spreadsheet of patient ID numbers outside the hospital. What fits?","A data loss prevention (DLP) policy."]],
  ["dlp"]),
C("records-management",10,"Compliance","4.3","Data lifecycle","Records management",
  ["Declares important items as records using retention labels.","Records are locked against deletion, and restricted from editing, during retention.","Supports disposition review at the end of retention."],
  "\"Must not be changed or deleted\" points to a record.",
  [["term","What happens when an item is declared a record?","It's locked against editing and deletion for its retention period."],
   ["use","Signed contracts must be kept unaltered for seven years, then reviewed before deletion. What fits?","Records management with a retention label and disposition review."]],
  ["records"]),
C("retention",10,"Compliance","4.3","Data lifecycle","Retention policies and retention labels",
  ["Retention keeps content for a period, deletes it, or both.","Retention policies apply broadly to locations, such as all mailboxes.","Retention labels apply to individual items.","Labels reach users through retention label policies or auto-apply."],
  "Whole locations point to a policy; specific items point to a label.",
  [["term","Retention policy or retention label: which applies to individual items?","A retention label."],
   ["use","Every Teams chat in the company should be deleted after two years. Policy or label?","A retention policy applied to the Teams location."]],
  ["retention"],{more:"When settings conflict, retention wins over deletion and the longest retention period wins."}),
// ---- Level 10 · 4.4 insider risk, eDiscovery, audit
C("insider-risk",10,"Compliance","4.4","Risk and investigations","Insider risk management",
  ["Detects risky activity by people inside the organization.","Example: a departing employee downloading large amounts of data.","Uses policy templates and signals such as HR data.","Usernames are pseudonymized by default for privacy."],
  "Risky actions by insiders point to insider risk management.",
  [["term","Why are usernames pseudonymized by default in insider risk management?","To protect privacy and reduce bias during investigations."],
   ["use","After resigning, an engineer copies hundreds of design files to a USB drive. Which Purview solution flags this?","Insider risk management."]],
  ["irm"]),
C("ediscovery",10,"Compliance","4.4","Risk and investigations","eDiscovery",
  ["Finds content for legal cases and investigations.","Places holds so relevant content is preserved.","Reviews and exports results.","Content search is part of eDiscovery."],
  "Legal case, preserve content, export for lawyers: think eDiscovery.",
  [["term","What does an eDiscovery hold do?","Preserves relevant content so it can't be permanently deleted while a case is open."],
   ["use","The school district's lawyers need every email about a contract preserved and exported. What fits?","eDiscovery (hold, then search and export)."]],
  ["ediscovery"]),
C("audit",10,"Compliance","4.4","Risk and investigations","Audit",
  ["Records user and admin activity across Microsoft 365.","Audit (Standard) keeps records for 180 days.","Audit (Premium) keeps core records (Exchange, SharePoint, Entra ID) for one year by default.","Helps investigations answer who did what, and when."],
  "Who did what and when points to audit.",
  [["term","How long does Audit (Standard) retain audit records?","180 days."],
   ["use","An intrusion is found 10 months after it began. Which audit tier still holds the Exchange records by default?","Audit (Premium): one year by default, versus 180 days for Audit (Standard)."]],
  ["audit"],{more:"Audit (Premium) also adds longer-retention policies (up to 10 years with an add-on license) and higher API bandwidth. OneDrive records follow the same one-year default."})
];

(window.CN_PACKS=window.CN_PACKS||[]).push({id:"sc-1",cert:"sc",label:"SC-900 batch 1",version:"2.1.0",reviewed:REV,objectives:O,studyGuide:S.studyGuide,concepts});
})();
