// Course material for each level (v2.3.0): the matching Microsoft Learn modules for SC-900, opened
// and checked on 2026-10-02. Titles are Microsoft's module titles. `focus` names the units in that
// module that match the level. Security+ levels 13-33 link the matching Professor Messer SY0-701 videos (each URL returned 200 on 2026-10-02) and name the CompTIA SY0-701 objectives.
(function(){
const M="https://learn.microsoft.com/en-us/training/modules/", P="https://learn.microsoft.com/en-us/training/paths/";
const mod=(slug,title,focus)=>({title:title,url:M+slug+"/",focus:focus||null,kind:"module"});
const path=(slug,title)=>({title:title,url:P+slug+"/",focus:null,kind:"path"});
const MS="https://www.professormesser.com/security-plus/sy0-701/sy0-701-video/";
const msr=(slug,title)=>({title:"Professor Messer: "+title,url:MS+slug+"/",focus:null,kind:"video"});
const msc=()=>({title:"Professor Messer: SY0-701 full course index",url:MS+"sy0-701-comptia-security-plus-course/",focus:"Pick the videos for the objectives you are reviewing",kind:"video"});
const obj=n=>({title:"CompTIA Security+ SY0-701",url:"https://www.comptia.org/en-us/certifications/security/",focus:/^all/.test(n)?"Objectives: "+n+". Videos and notes follow CompTIA's objective numbers":"SY0-701 objectives "+n+". Videos and notes follow CompTIA's objective numbers",kind:"guide"});
window.COURSE_LINKS={
  1:[mod("describe-security-concepts-methodologies","Describe security and compliance concepts","Units on shared responsibility, defense in depth and Zero Trust")],
  2:[mod("describe-security-concepts-methodologies","Describe security and compliance concepts","Units on encryption and hashing, and GRC"),
     mod("describe-identity-principles-concepts","Describe identity concepts")],
  3:[mod("explore-basic-services-identity-types","Describe the function and identity types of Microsoft Entra ID")],
  4:[mod("explore-authentication-capabilities","Describe the authentication capabilities of Microsoft Entra ID")],
  5:[mod("explore-access-management-capabilities","Describe access management capabilities of Microsoft Entra"),
     mod("describe-identity-protection-governance-capabilities","Describe the identity protection and governance capabilities of Microsoft Entra")],
  6:[path("describe-concepts-of-security-compliance-identity","SC-900 part 1: security, compliance, and identity concepts"),
     path("describe-capabilities-of-microsoft-identity-access","SC-900 part 2: Microsoft Entra")],
  7:[mod("describe-basic-security-capabilities-azure","Describe core infrastructure security services in Azure"),
     mod("describe-security-management-capabilities-of-azure","Describe the security management capabilities in Azure")],
  8:[mod("describe-security-capabilities-of-azure-sentinel","Describe security capabilities of Microsoft Sentinel"),
     mod("describe-threat-protection-with-microsoft-365-defender","Describe threat protection with Microsoft Defender XDR")],
  9:[mod("describe-compliance-management-capabilities-microsoft","Describe Microsoft's Service Trust Portal and privacy principles"),
     mod("describe-purview-risk-compliance-governance","Describe the data compliance solutions of Microsoft Purview","Unit on Compliance Manager"),
     mod("describe-purview-data-solutions","Describe the data security solutions of Microsoft Purview","Units on data classification, sensitivity labels and DLP")],
  10:[mod("describe-purview-risk-compliance-governance","Describe the data compliance solutions of Microsoft Purview","Units on communication compliance, eDiscovery, audit, data lifecycle and records"),
      mod("describe-purview-data-solutions","Describe the data security solutions of Microsoft Purview","Unit on insider risk management")],
  11:[path("describe-capabilities-of-microsoft-security-solutions","SC-900 part 3: Microsoft security solutions"),
      path("describe-capabilities-of-microsoft-compliance-solutions","SC-900 part 4: Microsoft Purview and privacy"),
      {title:"SC-900 study guide: skills measured",url:"https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/sc-900",focus:null,kind:"guide"}],
  12:[{title:"SC-900 exam page: free practice assessment and exam sandbox",url:"https://learn.microsoft.com/en-us/credentials/certifications/exams/sc-900/",focus:"Take the practice assessment cold, and try the sandbox to see the question formats",kind:"exam"},
      {title:"SC-900 study guide: skills measured",url:"https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/sc-900",focus:null,kind:"guide"}],
  13:[msr("security-controls-sy0-701","Security Controls"),
      msr("the-cia-triad-sy0-701","The CIA Triad"),
      msr("non-repudiation-sy0-701","Non-repudiation"),
      msr("authentication-authorization-and-accounting-sy0-701","Authentication, Authorization, and Accounting"),
      msr("gap-analysis-sy0-701","Gap Analysis"),
      msr("zero-trust-sy0-701","Zero Trust"),
      msr("physical-security-sy0-701","Physical Security"),
      msr("deception-and-disruption-sy0-701","Deception and Disruption"),
      obj("1.1 and 1.2")],
  14:[msr("change-management-sy0-701","Change Management"),
      msr("technical-change-management-sy0-701","Technical Change Management"),
      msr("public-key-infrastructure-sy0-701","Public Key Infrastructure"),
      msr("encrypting-data-sy0-701","Encrypting Data"),
      msr("key-exchange-sy0-701","Key Exchange"),
      msr("encryption-technologies-sy0-701","Encryption Technologies"),
      msr("obfuscation-sy0-701","Obfuscation"),
      msr("hashing-and-digital-signatures-sy0-701","Hashing and Digital Signatures"),
      msr("blockchain-technology-sy0-701","Blockchain Technology"),
      msr("certificates-sy0-701","Certificates"),
      obj("1.3 and 1.4")],
  15:[msr("threat-actors-sy0-701","Threat Actors"),
      msr("common-threat-vectors-sy0-701","Common Threat Vectors"),
      msr("phishing-sy0-701","Phishing"),
      msr("impersonation-sy0-701","Impersonation"),
      msr("watering-hole-attacks-sy0-701","Watering Hole Attacks"),
      msr("other-social-engineering-attacks-sy0-701","Other Social Engineering Attacks"),
      obj("2.1 and 2.2")],
  16:[msr("memory-injections-sy0-701","Memory Injections"),
      msr("buffer-overflows-sy0-701","Buffer Overflows"),
      msr("race-conditions-sy0-701","Race Conditions"),
      msr("malicious-updates-sy0-701","Malicious Updates"),
      msr("operating-system-vulnerabilities-sy0-701","Operating System Vulnerabilities"),
      msr("sql-injection-sy0-701","SQL Injection"),
      msr("cross-site-scripting-sy0-701","Cross-site Scripting"),
      msr("hardware-vulnerabilities-sy0-701","Hardware Vulnerabilities"),
      msr("virtualization-vulnerabilities-sy0-701","Virtualization Vulnerabilities"),
      msr("cloud-specific-vulnerabilities-sy0-701","Cloud-specific Vulnerabilities"),
      msr("supply-chain-vulnerabilities-sy0-701","Supply Chain Vulnerabilities"),
      msr("misconfiguration-vulnerabilities-sy0-701","Misconfiguration Vulnerabilities"),
      msr("mobile-device-vulnerabilities-sy0-701","Mobile Device Vulnerabilities"),
      msr("zero-day-vulnerabilities-sy0-701","Zero-day Vulnerabilities"),
      obj("2.3")],
  17:[msr("an-overview-of-malware-sy0-701","An Overview of Malware"),
      msr("viruses-and-worms-sy0-701","Viruses and Worms"),
      msr("spyware-and-bloatware-sy0-701","Spyware and Bloatware"),
      msr("other-malware-types-sy0-701","Other Malware Types"),
      msr("physical-attacks-sy0-701","Physical Attacks"),
      msr("denial-of-service-sy0-701","Denial of Service"),
      msr("dns-attacks-sy0-701","DNS Attacks"),
      msr("wireless-attacks-sy0-701","Wireless Attacks"),
      msr("on-path-attacks-sy0-701","On-path Attacks"),
      msr("replay-attacks-sy0-701","Replay Attacks"),
      msr("malicious-code-sy0-701","Malicious Code"),
      msr("application-attacks-sy0-701","Application Attacks"),
      msr("cryptographic-attacks-sy0-701","Cryptographic Attacks"),
      msr("password-attacks-sy0-701","Password Attacks"),
      msr("indicators-of-compromise-sy0-701","Indicators of Compromise"),
      obj("2.4")],
  18:[msr("segmentation-and-access-control-sy0-701","Segmentation and Access Control"),
      msr("mitigation-techniques-sy0-701","Mitigation Techniques"),
      msr("hardening-techniques-sy0-701","Hardening Techniques"),
      obj("2.5")],
  20:[msr("cloud-infrastructures-sy0-701","Cloud Infrastructures"),
      msr("network-infrastructure-concepts-sy0-701","Network Infrastructure Concepts"),
      msr("other-infrastructure-concepts-sy0-701","Other Infrastructure Concepts"),
      msr("infrastructure-considerations-sy0-701","Infrastructure Considerations"),
      obj("3.1")],
  21:[msr("secure-infrastructures-sy0-701","Secure Infrastructures"),
      msr("intrusion-prevention-sy0-701","Intrusion Prevention"),
      msr("network-appliances-sy0-701","Network Appliances"),
      msr("port-security-sy0-701","Port Security"),
      msr("firewall-types-sy0-701","Firewall Types"),
      msr("secure-communication-sy0-701","Secure Communication"),
      obj("3.2")],
  22:[msr("data-types-and-classifications-sy0-701","Data Types and Classifications"),
      msr("states-of-data-sy0-701","States of Data"),
      msr("protecting-data-sy0-701","Protecting Data"),
      msr("resiliency-sy0-701","Resiliency"),
      msr("capacity-planning-sy0-701","Capacity Planning"),
      msr("recovery-testing-sy0-701","Recovery Testing"),
      msr("backups-sy0-701","Backups"),
      msr("power-resiliency-sy0-701","Power Resiliency"),
      obj("3.3 and 3.4")],
  23:[msr("secure-baselines-sy0-701","Secure Baselines"),
      msr("hardening-targets-sy0-701","Hardening Targets"),
      msr("securing-wireless-and-mobile-sy0-701","Securing Wireless and Mobile"),
      msr("wireless-security-settings-sy0-701","Wireless Security Settings"),
      msr("application-security-sy0-701","Application Security"),
      msr("asset-management-sy0-701","Asset Management"),
      msr("vulnerability-scanning-sy0-701","Vulnerability Scanning"),
      msr("threat-intelligence-sy0-701","Threat Intelligence"),
      msr("penetration-testing-sy0-701","Penetration Testing"),
      msr("analyzing-vulnerabilities-sy0-701","Analyzing Vulnerabilities"),
      msr("vulnerability-remediation-sy0-701","Vulnerability Remediation"),
      obj("4.1, 4.2 and 4.3")],
  24:[msr("security-monitoring-sy0-701","Security Monitoring"),
      msr("security-tools-sy0-701","Security Tools"),
      msr("firewalls-sy0-701","Firewalls"),
      msr("web-filtering-sy0-701","Web Filtering"),
      msr("operating-system-security-sy0-701","Operating System Security"),
      msr("secure-protocols-sy0-701","Secure Protocols"),
      msr("email-security-sy0-701","Email Security"),
      msr("monitoring-data-sy0-701","Monitoring Data"),
      msr("endpoint-security-sy0-701","Endpoint Security"),
      obj("4.4 and 4.5")],
  25:[msr("identity-and-access-management-sy0-701","Identity and Access Management"),
      msr("access-controls-sy0-701","Access Controls"),
      msr("multifactor-authentication-sy0-701","Multifactor Authentication"),
      msr("password-security-sy0-701","Password Security"),
      obj("4.6")],
  26:[msr("scripting-and-automation-sy0-701","Scripting and Automation"),
      msr("incident-response-sy0-701","Incident Response"),
      msr("incident-planning-sy0-701","Incident Planning"),
      msr("digital-forensics-sy0-701","Digital Forensics"),
      msr("log-data-sy0-701","Log Data"),
      obj("4.7, 4.8 and 4.9")],
  28:[msr("security-policies-sy0-701","Security Policies"),
      msr("security-standards-sy0-701","Security Standards"),
      msr("security-procedures-sy0-701","Security Procedures"),
      msr("security-considerations-sy0-701","Security Considerations"),
      msr("data-roles-and-responsibilities-sy0-701","Data Roles and Responsibilities"),
      obj("5.1")],
  29:[msr("risk-management-sy0-701","Risk Management"),
      msr("risk-analysis-sy0-701","Risk Analysis"),
      msr("risk-management-strategies-sy0-701","Risk Management Strategies"),
      msr("business-impact-analysis-sy0-701","Business Impact Analysis"),
      msr("third-party-risk-assessment-sy0-701","Third-party Risk Assessment"),
      msr("agreement-types-sy0-701","Agreement Types"),
      obj("5.2 and 5.3")],
  30:[msr("compliance-sy0-701","Compliance"),
      msr("privacy-sy0-701","Privacy"),
      msr("audits-and-assessments-sy0-701","Audits and Assessments"),
      msr("penetration-tests-sy0-701","Penetration Tests"),
      msr("security-awareness-sy0-701","Security Awareness"),
      msr("user-training-sy0-701","User Training"),
      obj("5.4, 5.5 and 5.6")],
  31:[msr("firewall-types-sy0-701","Firewall Types"),
      msr("port-security-sy0-701","Port Security"),
      msr("secure-protocols-sy0-701","Secure Protocols"),
      msr("log-data-sy0-701","Log Data"),
      obj("3.2, 4.5 and 4.9 (ports, firewall rules, logs)")],
  19:[msc(),obj("1.1 to 2.5 (Domains 1 and 2)")],
  27:[msc(),obj("3.1 to 4.9 (Domains 3 and 4)")],
  32:[msc(),obj("all five domains")],
  33:[msr("how-to-pass-your-sy0-701-security-exam","How to pass your SY0-701 Security+ exam"),
      obj("all objectives")]
};
window.COURSE_LINKS_CHECKED="2026-10-02";
window.COURSE_LINKS_SEC_CHECKED="2026-10-02";
})();
