// Question pack 2 — 208 additional questions, 8 per study day.
// Same shape as data-extra.js: window.EXTRA2[dayNumber] = [ [question, [4 options], correctIndex, why], ... ]
// Correct answer is always index 0 here; the quiz engine shuffles option order at runtime.
window.EXTRA2 = {

/* ======================= SC-900 ======================= */

/* Day 1 — CIA, shared responsibility, defense in depth, Zero Trust */
1:[
["A company publishes its price list publicly but must guarantee nobody can alter it. Which CIA principle matters most here?",["Integrity","Confidentiality","Availability","Authentication"],0,"The data is meant to be public, so confidentiality isn't the concern. Preventing unauthorized change is integrity."],
["Under the shared responsibility model, who patches the guest operating system on an Azure virtual machine (IaaS)?",["The customer","Microsoft","Neither; VMs don't need patching","The hardware vendor"],0,"In IaaS the customer manages the guest OS, including its patches. Microsoft handles the physical host."],
["Which of these is a physical layer control in defense in depth?",["Datacenter badge readers and fencing","Multifactor authentication","Network security groups","Disk encryption"],0,"Physical controls protect the building and hardware itself; the others sit at identity, network, and data layers."],
["Zero Trust says to 'assume breach'. In practice this means:",["Design so that a compromised account or device has a limited blast radius","Assume every user is malicious and block all access","Stop investigating incidents because breach is inevitable","Trust devices that have already been breached once"],0,"Assume breach drives segmentation, least privilege, and monitoring so one compromise doesn't spread."],
["Moving from on-prem servers to SaaS shifts responsibility how?",["The customer keeps data, devices, and identities; the provider takes on nearly everything else","The customer becomes responsible for the physical datacenter","The provider becomes responsible for the customer's user accounts","Responsibility is always split exactly 50/50"],0,"SaaS is the model where the provider handles the most, but data, devices, and identities never transfer."],
["Which pillar does a distributed denial-of-service attack primarily target?",["Availability","Confidentiality","Integrity","Non-repudiation"],0,"DDoS floods a service so legitimate users can't reach it, which attacks availability."],
["An organization requires every access request to be authenticated and authorized using all available data points, no matter where it originates. This is:",["Verify explicitly","Assume breach","Shared responsibility","Defense in depth"],0,"Verify explicitly means always authenticate and authorize based on all available signals."],
["Which statement about the six Zero Trust pillars is correct?",["They include identities, devices, applications, data, infrastructure, and networks","They include only identities and networks","They are the same as the CIA triad","They apply only to on-premises environments"],0,"Zero Trust is applied across all six of those areas, not just the network."]],

/* Day 2 — Encryption, hashing, GRC, identity concepts */
2:[
["Why is asymmetric encryption typically used to exchange a key rather than to encrypt large files?",["It is much slower than symmetric encryption for bulk data","It is less secure than symmetric encryption","It cannot encrypt files at all","It requires both parties to share one secret key"],0,"Asymmetric solves the key-exchange problem but is computationally slow, so bulk data uses symmetric encryption."],
["Two different inputs producing the same hash value is known as a:",["Collision","Salt","Key exchange","Digest rotation"],0,"A collision weakens a hashing algorithm, which is why older algorithms like MD5 are avoided."],
["Which statement about digital signatures is accurate?",["They provide integrity, authentication, and non-repudiation","They keep the message contents secret from everyone","They replace the need for a certificate authority","They use the recipient's private key"],0,"Signing proves who sent it and that it wasn't altered, and the sender can't credibly deny it."],
["In the GRC model, performing a formal assessment to identify and rank threats to the business falls under:",["Risk","Governance","Compliance","Availability"],0,"Risk management is the identification, assessment, and treatment of threats."],
["A user proves who they are with a smart card, and then the system checks a permissions list. The permissions check is:",["Authorization","Authentication","Identification","Federation"],0,"Authentication proves identity; authorization determines what that identity may do."],
["Why is 'identity is the new perimeter' a common phrase in cloud security?",["Users and resources are distributed, so identity rather than network location controls access","Firewalls no longer exist in cloud environments","Networks are inherently secure in the cloud","Physical security has become irrelevant"],0,"With remote work and cloud resources, the network boundary no longer defines trust; identity does."],
["What does a directory service primarily provide?",["A central store of information about users, groups, devices, and their attributes","Encryption of data at rest","Automated incident response","Physical access control to buildings"],0,"A directory stores and organizes identity objects and their attributes."],
["Salting a password before hashing primarily prevents:",["Attackers from using precomputed hash tables against many accounts at once","The password from being typed incorrectly","The hash from being stored in a database","Users from reusing passwords"],0,"Unique salts mean identical passwords hash differently, defeating precomputed rainbow tables."]],

/* Day 3 — Entra ID: tenants, identity types, hybrid, external */
3:[
["What is a Microsoft Entra tenant?",["A dedicated, isolated instance of Entra ID representing one organization","A single user account","A physical datacenter in a region","A subscription billing plan"],0,"Each organization gets its own tenant, which is its dedicated directory instance."],
["Which identity type is automatically managed by Azure and tied to the lifecycle of a specific resource?",["A system-assigned managed identity","A user-assigned managed identity","A guest user","A security group"],0,"System-assigned identities are created with the resource and deleted when it is deleted."],
["What is the main advantage of a user-assigned managed identity over a system-assigned one?",["It exists independently and can be shared across multiple resources","It never requires any permissions","It works only for a single resource","It stores passwords in code"],0,"User-assigned identities are standalone objects reusable by many resources."],
["A Microsoft 365 group differs from a security group primarily because it:",["Provides shared collaboration resources like a mailbox and calendar in addition to access","Cannot be used for any access control","Can only contain guest users","Exists only on-premises"],0,"Microsoft 365 groups are collaboration-oriented, bundling a mailbox, calendar, and site."],
["An organization wants users to authenticate against on-premises Active Directory while accessing cloud apps. This arrangement is called:",["Hybrid identity","Pure cloud identity","Federated guest access","Shadow IT"],0,"Hybrid identity spans on-premises AD and Entra ID so users have one identity."],
["Which device state applies to a company laptop that is joined to on-premises AD and also registered in Entra ID?",["Microsoft Entra hybrid joined","Microsoft Entra joined","Microsoft Entra registered","Unmanaged"],0,"Hybrid join covers devices joined to on-prem AD and registered with Entra ID."],
["Microsoft Entra External ID is designed for:",["Collaborating with partners and providing identity for customer-facing apps","Managing on-premises domain controllers","Encrypting data at rest in Azure Storage","Monitoring network traffic"],0,"External ID covers both B2B partner collaboration and customer identity scenarios."],
["An application registered in Entra ID needs its own identity to call an API. That identity object is the:",["Service principal","Managed group","Guest user","Administrative unit"],0,"A service principal is the local representation of an application in a tenant."]],

/* Day 4 — Authentication methods */
4:[
["Which authentication scenario is NOT true multifactor authentication?",["A password plus a security question","A password plus a fingerprint","A PIN plus a hardware token","A password plus an Authenticator push approval"],0,"A password and a security question are both 'something you know', so only one factor type is used."],
["What makes FIDO2 security keys resistant to phishing?",["The credential is bound to the legitimate site's domain and won't work on a fake one","They generate longer passwords","They send a text message to the user","They require the user to memorize a passphrase"],0,"FIDO2 ties the credential to the origin, so a look-alike site cannot use it."],
["Windows Hello for Business authenticates using:",["A PIN or biometric tied to that specific device's secure hardware","A password stored in the cloud","A shared departmental password","A one-time code printed on paper"],0,"The credential never leaves the device and is protected by hardware such as a TPM."],
["Security defaults are best described as:",["A free, preconfigured baseline that cannot be customized per user or condition","A fully customizable policy engine","A premium feature requiring Entra ID P2","A replacement for all identity governance"],0,"Security defaults are all-or-nothing. Conditional Access is the customizable option."],
["For self-service password reset to work securely, users must first:",["Register authentication methods such as a phone or the Authenticator app","Contact the help desk for approval each time","Disable multifactor authentication","Join their device to the domain"],0,"Registration of verification methods is a prerequisite for SSPR."],
["What is the main weakness of SMS-based verification codes?",["They can be intercepted through SIM swapping or network attacks","They are too slow to deliver","They require a smart card reader","They cannot be used on mobile phones"],0,"SMS is allowed but weakest, mainly because of SIM swap and interception risks."],
["Microsoft's global banned password list works by:",["Blocking known weak and commonly attacked passwords for all tenants","Letting each user pick their own banned words","Blocking any password shorter than 20 characters","Requiring passwords to change weekly"],0,"Microsoft maintains a global list based on observed attack telemetry."],
["Certificate-based authentication in Entra ID allows users to:",["Authenticate directly with an X.509 certificate instead of a password","Encrypt all of their email automatically","Bypass Conditional Access policies","Share one certificate across the organization"],0,"CBA is a phishing-resistant, passwordless method using certificates."]],

/* Day 5 — Conditional Access, roles, ID Protection, governance */
5:[
["Which of these is a Conditional Access 'signal' rather than a decision?",["The sign-in's IP location","Requiring multifactor authentication","Blocking access","Granting access with a compliant device"],0,"Signals are inputs such as user, location, device, app, and risk. The rest are decisions."],
["What does 'report-only' mode in Conditional Access do?",["Logs what the policy would have done without enforcing it","Blocks all access silently","Applies the policy to administrators only","Deletes the policy after evaluation"],0,"Report-only lets you test a policy's impact before turning it on."],
["Entra ID Protection classifies risk into which two categories?",["User risk and sign-in risk","Device risk and network risk","Data risk and app risk","Physical risk and logical risk"],0,"User risk reflects a compromised identity; sign-in risk reflects a suspicious authentication attempt."],
["Which risk detection indicates credentials were found in a public breach dump?",["Leaked credentials","Atypical travel","Anonymous IP address","Unfamiliar sign-in properties"],0,"Leaked credentials means the username and password appeared in a known breach."],
["An access package in entitlement management can include:",["Groups, applications, and SharePoint sites bundled together","Only a single user account","Only on-premises file shares","Only administrative roles"],0,"Access packages bundle the resources a role needs, with policies for request and expiry."],
["What happens at the end of a PIM activation period?",["The elevated role assignment expires automatically","The user keeps the role permanently","The account is deleted","The tenant is locked"],0,"PIM assignments are time-bound and expire without manual cleanup."],
["Identity lifecycle management in Entra ID Governance addresses:",["Joiner, mover, and leaver processes for identities","Only password complexity rules","Physical badge issuance","Network firewall rules"],0,"Lifecycle management automates access as people join, change roles, and leave."],
["Microsoft Entra Private Access is best described as:",["Identity-aware access to internal applications without a traditional VPN","A public DNS filtering service","A database encryption feature","A backup solution for Entra ID"],0,"Private Access is part of Global Secure Access, replacing legacy VPN patterns for internal apps."]],

/* Day 7 — Azure infrastructure security + Defender for Cloud */
7:[
["A network security group rule is evaluated based on:",["Priority order, with the lowest-numbered matching rule applied first","Alphabetical order of rule names","The order rules were created","Random selection"],0,"NSG rules are processed by priority; the first match wins."],
["Which Azure DDoS Protection tier provides telemetry, alerting, and cost protection for specific resources?",["The paid protection tier (Network/IP Protection)","The free infrastructure-level tier","Azure Firewall Basic","Azure Bastion"],0,"The always-on free tier protects the platform; paid tiers add per-resource tuning, telemetry, and support."],
["Azure Firewall differs from a network security group mainly because it:",["Supports FQDN and application rules, threat intelligence filtering, and central policy across networks","Is the only one of the two that tracks connection state","Runs as an agent on each virtual machine","Cannot log traffic"],0,"Both are stateful, so that is not the difference. Azure Firewall adds FQDN/application awareness, threat intelligence, and centralized policy."],
["What problem does Azure Bastion solve?",["Administrative access to VMs without exposing public IP addresses or RDP/SSH ports","Encrypting data at rest on managed disks","Detecting phishing email","Managing compliance assessments"],0,"Bastion provides browser-based RDP/SSH over TLS through the portal."],
["Microsoft Defender for Cloud's Secure Score is calculated from:",["Compliance with recommended security controls in the Microsoft cloud security benchmark","The number of users in the tenant","The monthly Azure spend","Network bandwidth usage"],0,"Secure Score measures how many recommended controls are satisfied."],
["Cloud security posture management (CSPM) primarily focuses on:",["Finding misconfigurations and compliance drift across cloud resources","Blocking inbound network packets in real time","Encrypting email in transit","Issuing user certificates"],0,"CSPM identifies configuration weaknesses and provides remediation guidance."],
["Cloud workload protection (CWP) in Defender for Cloud provides:",["Threat detection for servers, containers, databases, and storage","A list of regulatory certifications","Password reset functionality","Identity governance workflows"],0,"CWP plans protect running workloads with threat detection and response."],
["Azure Key Vault supports which of the following?",["Secrets, keys, and certificates with access policies or RBAC","Only TLS certificates","Only storage account keys","Virtual machine disk images"],0,"Key Vault centrally manages secrets, cryptographic keys, and certificates."]],

/* Day 8 — Sentinel, Defender XDR, threat intelligence */
8:[
["In Microsoft Sentinel, what brings log data in from sources like Azure, Microsoft 365, and third-party products?",["Data connectors","Workbooks","Playbooks","Hunting queries"],0,"Data connectors ingest telemetry into the Sentinel workspace."],
["What are Sentinel analytics rules responsible for?",["Detecting suspicious patterns in ingested data and generating alerts or incidents","Displaying dashboards","Storing archived logs","Assigning user licenses"],0,"Analytics rules are the detection logic that turns raw data into alerts."],
["Which query language is used for hunting and analytics in Microsoft Sentinel?",["Kusto Query Language (KQL)","SQL Server T-SQL","PowerShell DSC","YAML"],0,"KQL is the query language across Sentinel and Defender advanced hunting."],
["What does the SOAR part of Sentinel add beyond SIEM?",["Automated orchestration and response to alerts","Longer log retention only","Hardware firewall management","User license provisioning"],0,"SOAR automates response, typically through playbooks built on Logic Apps."],
["Microsoft Defender XDR correlates signals across which areas?",["Endpoints, email and collaboration, identities, and cloud apps","Only endpoints","Only email","Only on-premises servers"],0,"XDR unifies detection and response across those domains into shared incidents."],
["Defender Vulnerability Management primarily provides:",["Discovery, assessment, and prioritization of software weaknesses on devices","Automated email quarantine","Network packet capture","Regulatory audit reports"],0,"It inventories software and surfaces vulnerabilities with risk-based prioritization."],
["Which Defender XDR capability lets analysts search historical data proactively for threats no alert has flagged?",["Advanced hunting","Attack simulation training","Secure Score","Compliance Manager"],0,"Advanced hunting queries raw telemetry across the estate, typically with KQL."],
["The Microsoft Defender portal is best described as:",["A single place to see incidents, alerts, and hunting across the Defender products","A billing dashboard for Azure","A replacement for Microsoft Purview","A tool for provisioning user licenses"],0,"The Defender portal unifies the XDR experience across endpoints, email, identity, and cloud apps."]],

/* Day 9 — Purview part 1 */
9:[
["Which Microsoft privacy principle states that customers own and control their own data?",["Control","Transparency","Security","Legal protections"],0,"Control means the customer decides what happens with their data."],
["In Compliance Manager, an 'improvement action' is:",["A recommended task that raises your compliance score when completed","An automatically applied configuration change","A Microsoft-managed control you cannot influence","A record of a past audit"],0,"Improvement actions are the customer-side tasks that increase the score."],
["Controls in Compliance Manager are categorized as:",["Microsoft-managed, customer-managed, or shared","Mandatory or optional only","Physical or logical only","Free or paid"],0,"Responsibility for each control belongs to Microsoft, the customer, or both."],
["Activity explorer in Microsoft Purview shows:",["What actions users took on labeled or sensitive content","Where sensitive files are stored only","The compliance score history","Azure resource costs"],0,"Content explorer shows where sensitive items live; activity explorer shows the actions taken on them."],
["Sensitivity labels can be applied:",["Manually by users, automatically by policy, or recommended to users","Only manually","Only by Global Administrators","Only to email, never to files"],0,"Labels support manual, automatic, and recommended application."],
["A DLP policy tip is:",["An in-app notification that warns the user before they share sensitive content","A report sent to the compliance officer weekly","A permanent block with no explanation","A retention setting"],0,"Policy tips coach users at the moment of the risky action."],
["Which is a better fit for detecting a document that 'reads like' a legal contract with no fixed pattern?",["A trainable classifier","An exact data match sensitive information type","A retention policy","A firewall rule"],0,"Trainable classifiers learn from examples where no fixed pattern exists."],
["DLP policies in Microsoft Purview can protect content in:",["Exchange, SharePoint, OneDrive, Teams, and on endpoints","Exchange only","On-premises file servers only","Azure virtual machines only"],0,"Purview DLP spans Microsoft 365 workloads and endpoint devices."]],

/* Day 10 — Purview part 2 */
10:[
["The key difference between a retention policy and a retention label is that a label:",["Applies to individual items, while a policy applies broadly to locations","Always deletes content immediately","Cannot be applied automatically","Only works in Microsoft Teams"],0,"Labels are item-level; policies are container or location level."],
["Declaring content a 'record' in records management means:",["It is locked against editing or deletion until the retention period ends","It is deleted immediately","It is shared with all users","It is exported to Azure Storage"],0,"Records are immutable for their retention period."],
["Insider risk management pseudonymizes usernames by default in order to:",["Protect employee privacy while still surfacing risky activity","Prevent investigators from ever identifying users","Comply with export controls","Speed up the detection engine"],0,"Pseudonymization balances investigation needs against privacy."],
["Which scenario best fits communication compliance?",["Detecting offensive language in Teams messages","Detecting mass file downloads to a USB drive","Scanning Azure VMs for malware","Rotating encryption keys"],0,"Communication compliance inspects messages; insider risk watches actions."],
["eDiscovery (Premium) adds which capability over the standard experience?",["Advanced review sets, analytics, and custodian management","Only keyword search","Only mailbox exports","Only audit log access"],0,"Premium adds custodian workflows, review sets, and analytics for legal matters."],
["Audit (Premium) provides which advantage?",["Longer retention and access to additional high-value audit events","A lower price than Audit (Standard)","Automatic deletion of logs after 30 days","Replacement of eDiscovery"],0,"Premium extends retention and surfaces additional event types."],
["DSPM for AI is designed to help organizations:",["Understand and reduce sensitive data risk in how AI apps use their data","Train their own large language models","Replace Microsoft Sentinel","Encrypt Azure storage accounts"],0,"Data security posture management for AI gives visibility into sensitive data used with AI apps."],
["A legal hold placed through eDiscovery ensures that:",["Relevant content is preserved even if a user tries to delete it","Content is immediately exported to the legal team","All user accounts are disabled","Retention policies are removed"],0,"Holds preserve content in place regardless of user deletion or retention settings."]],

/* ======================= SECURITY+ SY0-701 ======================= */

/* Day 13 — Controls, CIA+AAA, Zero Trust planes, physical, deception */
13:[
["An employee security awareness training program is which control CATEGORY?",["Operational","Technical","Managerial","Physical"],0,"Operational controls are carried out by people day to day. Managerial controls are policies and risk processes."],
["A written risk assessment procedure is which control category?",["Managerial","Technical","Operational","Physical"],0,"Managerial controls govern how security is planned and overseen."],
["The 'accounting' in AAA refers to:",["Recording what an authenticated user did","Billing for cloud resources","Approving purchase orders","Counting the number of user accounts"],0,"Accounting logs activity so actions can be traced."],
["In Zero Trust architecture, the Policy Enforcement Point:",["Enforces the decision made by the control plane on the actual traffic or request","Decides whether access should be granted","Stores user passwords","Issues digital certificates"],0,"The policy engine decides; the enforcement point in the data plane applies that decision."],
["'Adaptive identity' in the Zero Trust control plane means:",["Access decisions consider context such as behavior, location, and risk, not just credentials","Users can change their own identity attributes","Identities are rotated daily","Each user has multiple usernames"],0,"Adaptive identity factors in contextual signals when evaluating requests."],
["'Threat scope reduction' in Zero Trust is achieved primarily by:",["Limiting what each identity and segment can reach","Increasing password length","Adding more firewalls at the perimeter only","Disabling logging to reduce noise"],0,"Narrowing access limits how far an attacker can move."],
["Bollards in front of a building entrance are intended to:",["Stop vehicles from ramming the structure","Detect unauthorized badge use","Record video of visitors","Authenticate employees"],0,"Bollards are a physical barrier against vehicle impact."],
["A honeyfile is best described as:",["A decoy document that triggers an alert when accessed","A compressed archive of logs","A backup of critical files","An encrypted password vault"],0,"Honeyfiles are bait; access to them signals an intruder."]],

/* Day 14 — Change management, cryptography, PKI */
14:[
["Why does change management require an impact analysis before approval?",["To identify dependencies and side effects the change could cause","To assign blame if the change fails","To reduce the cost of software licenses","To eliminate the need for testing"],0,"Impact analysis surfaces downstream effects on systems, services, and users."],
["Updating allow lists and deny lists after a change matters because:",["A new system or address may be blocked or wrongly permitted otherwise","It reduces electricity usage","It replaces the need for a firewall","It shortens the maintenance window"],0,"Stale lists cause outages or unintended access after changes."],
["Perfect forward secrecy ensures that:",["Compromise of a long-term key does not expose past session traffic","Passwords never need to be changed","All sessions use the same key","Certificates never expire"],0,"Ephemeral session keys mean past traffic stays protected even if the long-term key leaks."],
["A self-signed certificate is appropriate for:",["Internal testing or internal services where trust is manually established","Public e-commerce websites","Any internet-facing service","Replacing a certificate authority entirely"],0,"Browsers don't trust self-signed certs, so they suit internal or test use only."],
["Key escrow means:",["A trusted third party holds a copy of cryptographic keys for recovery","Keys are destroyed after each use","Keys are published publicly","Keys are stored only on the user's device"],0,"Escrow allows recovery but introduces a trust and compliance consideration."],
["A hardware security module (HSM) is typically used to:",["Generate, store, and manage large numbers of keys in a tamper-resistant appliance","Encrypt a single laptop's hard drive","Provide RDP access to servers","Filter web traffic"],0,"HSMs are dedicated appliances for enterprise key management."],
["Data masking differs from tokenization because masking:",["Obscures part of the real value while the original data remains in the system","Removes the real value and stores it in a separate vault","Is a form of hashing","Requires a certificate authority"],0,"Masking hides characters from view; tokenization substitutes the value entirely."],
["A blockchain's open public ledger provides which security property?",["Integrity through an append-only, verifiable transaction record","Confidentiality of all transactions","Guaranteed availability of all nodes","Automatic key escrow"],0,"The distributed ledger makes tampering evident, which supports integrity."]],

/* Day 15 — Threat actors, motivations, vectors, social engineering */
15:[
["Which threat actor is most likely motivated by philosophical or political beliefs rather than money?",["Hacktivist","Organized crime","Insider seeking profit","Unskilled attacker seeking notoriety"],0,"Hacktivists act on ideology or a cause."],
["What most distinguishes an insider threat from an external attacker?",["The insider already has legitimate authorized access","The insider always has more technical skill","The insider is always malicious","The insider never triggers alerts"],0,"Legitimate access is the defining characteristic, and it is why insiders are hard to detect."],
["An 'unskilled attacker' is dangerous mainly because:",["Powerful attack tools are freely available and easy to run","They have nation-state funding","They always work in organized groups","They write custom zero-day exploits"],0,"Off-the-shelf tooling lets low-skill attackers cause real damage."],
["A supply chain attack vector could involve:",["A compromised managed service provider with access to customer networks","An employee choosing a weak password","A user clicking a phishing link","An unpatched personal laptop"],0,"Supply chain attacks exploit trusted vendors, suppliers, and service providers."],
["Which is an example of a message-based attack vector?",["A malicious link delivered by instant message","A rogue USB drive left in a lobby","An unsecured Bluetooth pairing","An open port on a server"],0,"Message-based vectors include email, SMS, and instant messaging."],
["Brand impersonation differs from typosquatting because impersonation:",["Mimics the look and identity of a trusted company, not just a misspelled domain","Requires the victim to mistype a URL","Only occurs over the phone","Only targets executives"],0,"Brand impersonation copies logos, tone, and identity; typosquatting relies on URL typos."],
["Disinformation differs from misinformation because disinformation is:",["Spread deliberately with intent to deceive","Always shared by accident","Only found on social media","Always factually correct"],0,"Intent is the distinction: disinformation is deliberate."],
["An attacker researches an employee's job title, manager, and recent projects before calling them. This preparation is:",["Reconnaissance supporting a pretexting attack","A brute force attack","A denial of service","Privilege escalation"],0,"Gathering details makes the fabricated story credible."]],

/* Day 16 — Vulnerability types */
16:[
["Memory injection refers to:",["Inserting malicious code into the memory space of a running process","Filling a disk with junk data","Overwriting a database record","Flooding a network with packets"],0,"Attackers inject code into legitimate running processes to evade detection."],
["Which best describes a 'malicious update' vulnerability?",["A trusted software update mechanism is used to deliver compromised code","Users refuse to install updates","Updates are released too frequently","Updates require a reboot"],0,"The trusted update channel itself becomes the delivery path, as in supply chain compromises."],
["Why are end-of-life systems a significant vulnerability?",["The vendor no longer issues security patches for newly discovered flaws","They run more slowly than modern systems","They use more electricity","They cannot connect to networks"],0,"No vendor support means known vulnerabilities stay permanently unpatched."],
["Client-based software vulnerabilities differ from agentless ones because client-based:",["Requires installed software on each endpoint that must itself be maintained","Never requires updates","Cannot be exploited","Only applies to servers"],0,"Installed agents expand the attack surface and require their own patching."],
["A cloud misconfiguration commonly exploited by attackers is:",["A storage bucket left publicly readable","Excessively strong encryption","Too many multifactor prompts","Overly restrictive IAM policies"],0,"Publicly exposed storage is one of the most common cloud data-leak causes."],
["Jailbreaking or rooting a mobile device is a risk because it:",["Removes built-in OS security restrictions and sandboxing","Improves battery performance","Encrypts all device data","Enables multifactor authentication"],0,"It disables protections the OS relies on to isolate apps and data."],
["A hardware vulnerability in device firmware is concerning because firmware:",["Runs below the operating system and can persist through reinstalls","Is never targeted by attackers","Cannot be updated","Only affects printers"],0,"Firmware-level compromise survives OS reinstallation and is hard to detect."],
["Which statement about zero-day vulnerabilities is correct?",["No patch exists because the vendor is not yet aware of the flaw","They are always found in open-source software","They can be fixed by applying existing updates","They only affect legacy systems"],0,"Zero-day means the vendor has had zero days to fix it."]],

/* Day 17 — Malware, attacks, indicators */
17:[
["Bloatware is a concern primarily because it:",["Expands the attack surface with unnecessary preinstalled software","Encrypts user files for ransom","Spreads automatically across networks","Hides in the kernel"],0,"Unneeded preinstalled apps add unpatched code and potential vulnerabilities."],
["In a DNS amplification attack, the attacker:",["Sends small spoofed queries that generate large responses aimed at the victim","Deletes the victim's DNS records","Encrypts the victim's DNS server","Guesses the DNS administrator's password"],0,"The size difference between query and response amplifies the flood."],
["A deauthentication attack against Wi-Fi is used to:",["Force clients off a network, often to capture handshakes or push them to a rogue AP","Encrypt wireless traffic","Extend wireless range","Assign static IP addresses"],0,"Deauth frames disconnect clients, enabling capture or evil twin attacks."],
["Cross-site request forgery (CSRF) works by:",["Tricking an authenticated user's browser into submitting an unwanted request","Injecting SQL into a login form","Overflowing a memory buffer","Capturing packets on the wire"],0,"CSRF abuses the victim's existing authenticated session."],
["Server-side request forgery (SSRF) causes:",["The server to make requests to resources the attacker chooses","The client browser to run malicious script","A password database to be dumped","A physical door to unlock"],0,"SSRF turns the server into a proxy, often to reach internal services."],
["A downgrade attack succeeds by:",["Forcing communication to use a weaker, older protocol or cipher","Reducing the victim's bandwidth","Uninstalling antivirus software","Lowering user privileges"],0,"Downgrades push connections to protocols with known weaknesses."],
["'Out-of-cycle logging' as an indicator of compromise means:",["Log entries appear at unusual times that don't match normal operations","Logs are formatted incorrectly","Logs are stored in the wrong folder","Logs are compressed"],0,"Activity outside normal patterns suggests unauthorized action."],
["Missing logs are a strong indicator of compromise because:",["Attackers often delete logs to hide their activity","Logging always fails during business hours","Log storage is unlimited","Missing logs improve performance"],0,"Log deletion or gaps often signal anti-forensic activity."]],

/* Day 18 — Mitigation techniques */
18:[
["Least privilege applied to a service account means:",["The account has only the permissions its specific service requires","The account is a domain administrator for flexibility","The account password never expires","The account is shared across services"],0,"Service accounts should be scoped tightly to their function."],
["Why is an application allow list generally stronger than a deny list?",["Only explicitly approved software can run, blocking unknown threats by default","It is easier to maintain","It permits more applications","It requires no administration"],0,"Deny lists only stop known-bad; allow lists block everything unapproved, including novel malware."],
["Configuration enforcement helps security by:",["Automatically reapplying the approved baseline when systems drift","Allowing users to configure systems freely","Replacing the need for patching","Disabling all logging"],0,"Enforcement corrects drift so systems stay at their hardened baseline."],
["Proper decommissioning of a retired server should include:",["Sanitizing or destroying its storage and removing its access and accounts","Simply unplugging it and leaving it in the rack","Leaving its accounts active in case it returns","Only deleting the hostname from DNS"],0,"Data must be sanitized and associated access removed to avoid lingering exposure."],
["Host-based intrusion prevention differs from a network IPS because it:",["Runs on the endpoint and inspects activity on that specific host","Inspects all traffic on the network segment","Cannot block anything","Only applies to routers"],0,"HIPS protects an individual host; a network IPS protects a segment."],
["Disabling unused ports and protocols on a server is an example of:",["Reducing the attack surface through hardening","Increasing availability","Improving encryption strength","Configuring least privilege for users"],0,"Every open port or enabled protocol is a potential entry point."],
["Endpoint detection and response (EDR) adds what over traditional antivirus?",["Behavioral detection, investigation, and response capabilities on the endpoint","Only signature-based scanning","Physical security monitoring","Certificate issuance"],0,"EDR watches behavior and supports investigation and containment, not just signatures."],
["A patch should generally be tested before deployment because:",["It may break dependent applications or introduce instability","Patches are always malicious","Testing eliminates the need for backups","Vendors require it legally"],0,"Testing in a representative environment prevents patch-induced outages."]],

/* Day 20 — Architecture models */
20:[
["A key security risk of infrastructure as code is that:",["A flaw in a template is replicated across every deployment that uses it","Templates cannot be version controlled","It prevents consistent configuration","It requires manual provisioning"],0,"IaC multiplies both good and bad configurations at scale."],
["Serverless computing shifts which responsibility to the provider?",["Managing and patching the underlying server infrastructure","Securing the application code","Managing the customer's data","Controlling user access"],0,"The provider runs the infrastructure; the customer still owns code, data, and access."],
["A security concern specific to microservices architecture is:",["A larger number of network calls and APIs to secure between services","The inability to scale","Having only a single point of failure","No need for authentication"],0,"Splitting an app increases inter-service communication that must be secured."],
["Compared to virtual machines, containers generally have:",["A smaller footprint but shared kernel risk if the host is compromised","Complete hardware isolation","Their own separate operating system kernels","No need for image scanning"],0,"Shared-kernel architecture means a host compromise can affect all containers."],
["A real-time operating system (RTOS) is characterized by:",["Deterministic, time-critical processing for systems like medical and automotive devices","Running only in cloud datacenters","Supporting unlimited third-party applications","Requiring no security consideration"],0,"RTOS environments prioritize timing guarantees, which constrains security options."],
["Why are many embedded and IoT devices difficult to secure?",["Limited compute, infrequent vendor updates, and default credentials","They have too much processing power","They cannot connect to networks","They are always physically inaccessible"],0,"Constrained hardware and weak update practices leave known flaws in place."],
["'Risk transference' as an architecture consideration typically means:",["Shifting some risk to a provider or insurer through contracts or services","Eliminating the risk entirely","Ignoring the risk","Documenting the risk only"],0,"Using a managed service or insurance moves part of the burden elsewhere."],
["A high-availability architecture consideration that increases both cost and resilience is:",["Geographic dispersion of redundant systems","Running a single server with no backups","Disabling failover to reduce complexity","Consolidating everything into one datacenter"],0,"Spreading systems geographically protects against regional failures at higher cost."]],

/* Day 21 — Network security design */
21:[
["A reverse proxy differs from a forward proxy because it:",["Sits in front of servers and handles requests on their behalf","Is used only by client machines","Cannot terminate TLS","Only caches DNS records"],0,"Forward proxies serve clients going out; reverse proxies front the servers."],
["Why might an organization deploy an IDS rather than an IPS on a sensitive segment?",["To monitor without any risk of blocking legitimate critical traffic","Because IDS is always more accurate","Because IPS cannot detect attacks","Because IDS requires no tuning"],0,"Passive monitoring avoids the operational risk of false-positive blocking, which matters on critical systems."],
["802.1X port-based access control involves which three roles?",["Supplicant, authenticator, and authentication server","Client, firewall, and router","Proxy, gateway, and switch","Sender, receiver, and relay"],0,"The device supplicant authenticates through the switch (authenticator) to a RADIUS server."],
["IPsec transport mode differs from tunnel mode because transport mode:",["Encrypts only the payload, leaving the original IP header intact","Encrypts the entire original packet including headers","Cannot provide encryption","Is only used for site-to-site VPNs"],0,"Tunnel mode wraps the whole packet; transport mode protects just the payload."],
["Secure Access Service Edge (SASE) combines:",["Network connectivity and security functions delivered from the cloud","Only on-premises firewalls","Only endpoint antivirus","Physical access controls"],0,"SASE converges networking and security services in the cloud for distributed users."],
["A unified threat management (UTM) appliance is characterized by:",["Multiple security functions combined into a single device","A single dedicated function","Operating only at layer 2","Being software-only"],0,"UTM bundles firewall, IPS, antivirus, filtering, and more in one box."],
["Placing a device 'out-of-band' for monitoring means it:",["Receives a copy of traffic and cannot block it inline","Sits directly in the traffic path","Replaces the firewall","Only monitors physical access"],0,"Out-of-band taps or SPAN ports provide visibility without inline risk."],
["Why is port security on a switch useful?",["It limits which MAC addresses may use a physical port","It encrypts all traffic on the port","It assigns IP addresses","It provides DDoS protection"],0,"Port security restricts unauthorized devices from connecting to a physical port."]],

/* Day 22 — Data protection and resilience */
22:[
["Protecting 'data in use' is challenging because the data is:",["Decrypted in memory while being processed","Stored on disk in plaintext","Always transmitted over the network","Never accessible to applications"],0,"Data in use must be readable to be processed, which is why technologies like confidential computing exist."],
["Which data classification typically indicates the most restrictive handling?",["Restricted or critical","Public","Private","Internal"],0,"Restricted and critical classifications carry the strictest controls."],
["Protected health information (PHI) is an example of:",["Regulated data","Trade secret data","Public data","Intellectual property only"],0,"PHI is regulated under laws such as HIPAA."],
["Journaling in a backup context refers to:",["Recording changes so a system can be recovered to a specific point in time","Writing daily operations notes","Compressing archived data","Rotating encryption keys"],0,"Journaling logs transactions or changes to support point-in-time recovery."],
["A parallel processing test of a disaster recovery plan involves:",["Running production and recovery systems simultaneously to compare results","Only discussing the plan in a meeting","Shutting down production entirely","Restoring one file"],0,"Parallel processing validates the recovery environment against live production output."],
["Capacity planning for resilience should consider:",["People, technology, and infrastructure needed to sustain operations","Only server hardware","Only software licenses","Only network bandwidth"],0,"Resilience requires enough staff, systems, and facilities, not just hardware."],
["Replication differs from traditional backup because replication:",["Continuously copies data to another location, often in near real time","Runs only once per month","Cannot be automated","Always requires tape media"],0,"Replication keeps a near-current copy; backups are point-in-time snapshots."],
["Why should backups be encrypted?",["Backup media can be lost or stolen and contain complete copies of sensitive data","Encryption speeds up restoration","It is required for compression","It reduces storage costs"],0,"An unencrypted backup is a full copy of your data outside your primary controls."]],

/* Day 23 — Hardening, wireless, mobile, assets, vuln mgmt */
23:[
["A wireless site survey and heat map are used to:",["Plan access point placement and identify coverage gaps or rogue signals","Configure user passwords","Encrypt wireless traffic","Assign VLANs"],0,"Surveys map real signal coverage, informing placement and detecting unexpected transmitters."],
["WPA3 improves on WPA2 primarily through:",["Simultaneous Authentication of Equals (SAE) replacing the pre-shared key handshake","Removing encryption entirely","Using WEP for backward compatibility","Eliminating the need for passwords"],0,"SAE resists offline dictionary attacks that affected the WPA2 handshake."],
["Wireless enterprise authentication typically uses:",["802.1X with a RADIUS server and EAP","A single shared passphrase","Open authentication","MAC filtering only"],0,"Enterprise mode authenticates each user individually against RADIUS."],
["A credentialed vulnerability scan is preferred because it:",["Authenticates to the host and produces more accurate, deeper results","Runs faster than an unauthenticated scan","Requires no configuration","Cannot produce false positives"],0,"Logging in reveals patch levels and configuration details an external scan can't see."],
["A bug bounty program is:",["A structured way to pay external researchers for responsibly reported vulnerabilities","An internal patching schedule","A type of penetration test contract","A compliance certification"],0,"Bug bounties crowdsource vulnerability discovery with defined rules and rewards."],
["Degaussing is an appropriate sanitization method for:",["Magnetic media such as traditional hard drives and tapes","Solid-state drives","Optical discs","Paper documents"],0,"Degaussing disrupts magnetic fields and does not work on flash-based SSDs."],
["Asset 'ownership' in an inventory matters because:",["Someone must be accountable for each asset's security and lifecycle","It determines the purchase price","It is required for network addressing","It speeds up patching automatically"],0,"Clear ownership drives accountability for configuration, patching, and disposal."],
["Code signing provides assurance that:",["Software came from the stated publisher and hasn't been altered","The software is free of all bugs","The software is open source","The software will run on any platform"],0,"A valid signature verifies publisher identity and integrity, not quality."]],

/* Day 24 — Monitoring tools and enterprise capabilities */
24:[
["Alert tuning is important because:",["Excessive false positives cause analysts to miss genuine threats","It reduces log storage costs only","It disables all alerts","It replaces the need for a SIEM"],0,"Alert fatigue is a real operational risk; tuning preserves attention for real detections."],
["Security Content Automation Protocol (SCAP) is used to:",["Automate configuration and vulnerability checking using standardized formats","Encrypt network traffic","Provision user accounts","Manage physical badges"],0,"SCAP standardizes how security configuration and vulnerability data are expressed and checked."],
["A benchmark such as the CIS Benchmarks provides:",["Consensus-based secure configuration guidance for specific systems","A list of active threat actors","Legal compliance certification","Network bandwidth measurements"],0,"Benchmarks give concrete hardening settings per platform."],
["Agent-based monitoring differs from agentless because agent-based:",["Installs software on each endpoint for deeper, continuous visibility","Requires no endpoint configuration","Only works over the network","Cannot collect real-time data"],0,"Agents provide richer local telemetry at the cost of deployment and maintenance."],
["SNMP traps are:",["Unsolicited alerts sent by network devices when defined events occur","Encrypted tunnels between routers","Physical security devices","Log archival formats"],0,"Traps push notifications from devices rather than waiting to be polled."],
["DNS filtering protects users by:",["Blocking resolution of known malicious domains before a connection is made","Encrypting all DNS queries","Assigning static IP addresses","Scanning email attachments"],0,"Blocking at the lookup stage stops the connection from ever being established."],
["Group Policy in Windows environments is used to:",["Centrally enforce security and configuration settings across domain systems","Encrypt individual files","Monitor network packets","Issue TLS certificates"],0,"Group Policy pushes standardized configuration across the domain."],
["SELinux provides which capability on Linux systems?",["Mandatory access control enforcement at the operating system level","Antivirus scanning","Network intrusion prevention","Disk defragmentation"],0,"SELinux enforces MAC policies constraining what processes may access."]],

/* Day 25 — Identity and access management */
25:[
["Discretionary access control (DAC) is characterized by:",["The data owner deciding who may access their resources","Administrators assigning clearance labels","Access based on job role only","Access based on time of day only"],0,"In DAC the owner sets permissions, as with typical file sharing."],
["Role-based access control assigns permissions based on:",["The user's job function within the organization","The user's physical location","The time of the request","Data sensitivity labels"],0,"RBAC groups permissions by role, simplifying administration."],
["SAML is primarily used for:",["Exchanging authentication and authorization data between an identity provider and a service provider","Encrypting files at rest","Scanning for vulnerabilities","Managing network switches"],0,"SAML is the XML-based standard behind much enterprise web SSO."],
["OpenID Connect relates to OAuth 2.0 because OIDC:",["Adds an authentication layer on top of OAuth's authorization framework","Replaces OAuth entirely","Is an older protocol OAuth replaced","Performs only encryption"],0,"OAuth handles delegated authorization; OIDC adds identity verification."],
["LDAP over TLS (LDAPS) uses which port by default?",["636","389","443","3268"],0,"LDAP is 389; LDAPS is 636."],
["Identity proofing during onboarding means:",["Verifying that a person is who they claim to be before issuing credentials","Testing the strength of their password","Scanning their device for malware","Reviewing their access quarterly"],0,"Proofing establishes real-world identity before an account exists."],
["Attestation in identity management refers to:",["Periodically confirming that existing access is still appropriate","Issuing a new certificate","Encrypting a password database","Creating a new user account"],0,"Attestation is the recurring confirmation of continued need for access."],
["Ephemeral credentials are valuable because they:",["Expire automatically after a short time, limiting the window for misuse","Never change, simplifying automation","Are shared across the whole team","Are stored in plaintext for convenience"],0,"Short-lived credentials shrink the exposure window if they leak."]],

/* Day 26 — Automation, IR, forensics, data sources */
26:[
["'Guard rails' in security automation refer to:",["Automated constraints that prevent unsafe configurations from being deployed","Physical barriers in a datacenter","Manual approval of every change","Firewall rules only"],0,"Guard rails automatically enforce policy boundaries during provisioning."],
["A significant downside of heavy security automation is:",["Complexity and the risk of a single point of failure","Slower incident response","Inability to enforce baselines","Higher staffing requirements"],0,"Automation adds complexity, technical debt, and dependency on the automation itself."],
["During the analysis phase of incident response, the team primarily:",["Determines scope, impact, and root cause of the incident","Rebuilds affected systems","Writes the final executive report","Purchases new hardware"],0,"Analysis characterizes what happened and how far it spread before containment decisions."],
["Eradication in incident response means:",["Removing the threat, such as malware and attacker persistence, from the environment","Disconnecting the network cable","Restoring normal operations","Documenting lessons learned"],0,"Eradication removes the attacker's presence before recovery begins."],
["The purpose of a tabletop exercise is to:",["Walk through a scenario in discussion to test the plan without touching systems","Physically fail over to a backup datacenter","Scan for vulnerabilities","Rebuild a compromised server"],0,"Tabletops validate decision-making and roles at low cost and low risk."],
["Root cause analysis after an incident aims to:",["Identify the underlying cause so the same failure doesn't recur","Assign blame to an individual","Restore systems faster","Satisfy the insurance company only"],0,"RCA targets the systemic cause, not just the symptom."],
["E-discovery in a forensic context refers to:",["Identifying, collecting, and producing electronic information for legal proceedings","Discovering new devices on the network","Scanning for vulnerabilities","Deploying endpoint agents"],0,"E-discovery is the legal process of producing electronically stored information."],
["Which data source would best show which external IP addresses a host communicated with over the past week?",["Firewall and network flow logs","Physical badge records","Application source code","The asset inventory spreadsheet"],0,"Firewall and flow logs record connection metadata over time."]],

/* Day 28 — Governance, policies, data roles */
28:[
["A business continuity policy differs from a disaster recovery policy because continuity focuses on:",["Keeping essential business functions operating during a disruption","Restoring IT systems after a failure","Encrypting sensitive data","Managing user passwords"],0,"BC keeps the business running; DR restores the technology."],
["A software development lifecycle (SDLC) policy exists to:",["Build security requirements and reviews into how software is created","Define acceptable use of email","Schedule datacenter maintenance","Set password length"],0,"An SDLC policy embeds security into design, development, testing, and release."],
["A data steward is typically responsible for:",["Day-to-day data quality, labeling, and adherence to handling standards","Setting the overall classification and accountability","Processing data on behalf of a controller","Auditing the organization externally"],0,"Stewards handle practical data management; owners hold accountability."],
["Centralized governance means:",["Decisions and standards are set by one authoritative body for the whole organization","Each department sets its own independent rules","No governance structure exists","Governance is outsourced to a vendor"],0,"Centralized structures give consistency; decentralized gives local flexibility."],
["Which external consideration would most directly force a change to data storage location?",["A national or regional data residency law","An industry conference recommendation","An internal style guide","A vendor marketing claim"],0,"Data residency and sovereignty laws dictate where data may physically live."],
["A playbook in a security operations context is best classified as a:",["Procedure","Policy","Guideline","Standard"],0,"Playbooks are step-by-step procedures for handling specific situations."],
["Monitoring and revision of policies matters because:",["Threats, regulations, and business needs change over time","Policies are legally required to change monthly","It reduces the number of employees needed","Auditors ignore outdated policies"],0,"Static policies drift out of alignment with reality and regulation."],
["An onboarding procedure from a security perspective should include:",["Account provisioning with least privilege and acceptable use acknowledgment","Only issuing a laptop","Only a building tour","Only payroll setup"],0,"Security onboarding covers appropriate access and policy acknowledgment."]],

/* Day 29 — Risk management, BIA, third parties */
29:[
["A risk register typically contains:",["Identified risks, owners, impact, likelihood, and treatment decisions","Only completed audits","Employee performance reviews","Network topology diagrams"],0,"The register is the living record of risks and how they are being handled."],
["A key risk indicator (KRI) is used to:",["Provide an early warning signal that risk exposure is increasing","Measure employee productivity","Calculate annual revenue","Replace the risk register"],0,"KRIs are metrics watched against thresholds to flag rising risk."],
["An organization with a 'conservative' risk appetite is most likely to:",["Accept less risk, favoring stronger controls even at higher cost","Pursue aggressive new ventures with minimal controls","Ignore risk assessments","Transfer all risk to customers"],0,"Appetite describes how much risk the organization is willing to pursue."],
["Mean time between failures (MTBF) measures:",["Average time a system operates before failing","How long repairs take","Maximum acceptable data loss","Maximum acceptable downtime"],0,"MTBF is a reliability metric; MTTR measures repair time."],
["A quantitative risk assessment is distinguished by:",["Assigning specific monetary values to assets, losses, and likelihood","Using high, medium, and low ratings","Relying only on expert opinion","Avoiding numbers entirely"],0,"Quantitative analysis produces dollar figures such as SLE and ALE."],
["A vendor questionnaire during due diligence is used to:",["Gather evidence about the vendor's security practices before engagement","Negotiate the final price","Replace a signed contract","Terminate an existing agreement"],0,"Questionnaires collect structured information to assess third-party risk."],
["A master service agreement (MSA) establishes:",["General terms that govern future individual engagements","The specific deliverables for one project","Confidentiality obligations only","Guaranteed uptime percentages"],0,"MSAs set the overarching terms; SOWs define specific work."],
["Which document defines the specific deliverables, timeline, and scope for one project?",["Statement of work (SOW)","Master service agreement","Memorandum of understanding","Non-disclosure agreement"],0,"The SOW details what will be delivered for a particular engagement."]],

/* Day 30 — Compliance, audits, pen testing, awareness */
30:[
["A consequence of non-compliance that directly threatens an organization's ability to operate is:",["Loss of license or certification","A negative social media post","An internal memo","A delayed software release"],0,"Losing required licensure can stop the business from legally operating."],
["An internal audit differs from an external audit primarily because internal audits are:",["Conducted by the organization's own staff or audit committee","Always required by law","Performed only by regulators","Never documented"],0,"Internal audits are self-assessments; external audits are performed by independent parties."],
["An attestation in a compliance context is:",["A formal statement confirming that controls are in place and operating","A vulnerability scan report","A network diagram","An employee performance review"],0,"Attestations formally affirm compliance status, often signed by a responsible party."],
["Rules of engagement for a penetration test define:",["Scope, timing, permitted techniques, and communication procedures","The final report format only","The tester's salary","The organization's risk appetite"],0,"RoE set the boundaries so testing is authorized, safe, and legally protected."],
["A partially known environment penetration test means testers have:",["Some information, such as network ranges but not full architecture details","Complete source code and diagrams","No information at all","Only physical building access"],0,"Partially known (gray box) sits between white and black box."],
["Why is recurring security awareness training more effective than a one-time session?",["Threats evolve and reinforcement counters knowledge decay","It satisfies auditors regardless of content","It replaces technical controls","It reduces the training budget"],0,"Regular reinforcement keeps skills current against changing tactics."],
["Reporting anomalous behavior should be encouraged because:",["Employees often notice suspicious activity before automated tools do","It reduces the number of security tools needed","It assigns blame quickly","It eliminates the need for monitoring"],0,"People are an important detection layer when reporting is easy and blame-free."],
["Operational security (OPSEC) awareness training teaches employees to:",["Avoid disclosing information that could help an attacker","Configure firewalls","Write secure code","Perform forensic analysis"],0,"OPSEC focuses on protecting seemingly harmless details that aid attackers."]],

/* Day 31 — Ports, logs, firewall rules */
31:[
["Which port does Telnet use?",["23","22","21","25"],0,"Telnet is 23 and transmits in cleartext; SSH (22) is its secure replacement."],
["Which ports does FTP use for control and data?",["21 for control and 20 for data","22 and 23","80 and 443","137 and 139"],0,"FTP control traffic uses 21; active-mode data uses 20."],
["Which port does SNMP use for traps?",["162","161","514","69"],0,"SNMP polling is 161; traps are sent to 162."],
["Which port does syslog typically use?",["514","161","443","3389"],0,"Syslog listens on UDP 514 by default."],
["Which port does Microsoft SQL Server use by default?",["1433","3306","5432","1521"],0,"SQL Server uses 1433; MySQL is 3306 and PostgreSQL is 5432."],
["Which ports does Kerberos authentication use?",["88","389","445","53"],0,"Kerberos uses port 88."],
["A firewall rule set ends with an implicit deny. This means:",["Traffic not explicitly permitted by an earlier rule is blocked","All traffic is allowed by default","The last rule is ignored","Logging is disabled"],0,"Anything that reaches the bottom without matching an allow is denied."],
["A log shows repeated successful logins to a service account at 3 AM from a new IP, followed by large outbound transfers. The best interpretation is:",["Possible account compromise and data exfiltration","Normal scheduled maintenance","A false positive from the scanner","A hardware failure"],0,"Off-hours access from a new source plus large outbound volume is a classic exfiltration pattern."]]
};
