// Question pack 3 — 219 questions, weighted by real exam domain percentages.
// SC-900: security solutions 35-40%, Entra 25-30%, compliance 20-25%, concepts 10-15%
// Sec+:   operations 28%, threats 22%, program mgmt 20%, architecture 18%, general 12%
// Shape matches data-extra.js / data-pack2.js. Correct answer is index 0; the engine shuffles at runtime.
window.EXTRA3 = {

/* ======================= SC-900 ======================= */

/* Day 1 — Concepts (light weight: 10-15%) */
1:[
["In PaaS, who is responsible for configuring access controls on the application the customer builds?",["The customer","Microsoft","The platform automatically","No one"],0,"The provider runs the platform, but the customer always owns their data, identities, and access configuration."],
["'Verify explicitly' means access decisions should be based on:",["All available data points, including identity, device health, location, and behavior","The user's password alone","Whether the request came from inside the office","The time of day only"],0,"Explicit verification uses every available signal rather than one credential."],
["A backup system that lets a company restore service after a ransomware attack primarily supports:",["Availability","Confidentiality","Non-repudiation","Authorization"],0,"Backups restore access to data and systems, which is the availability pillar."],
["Encrypting a database and restricting who holds the keys is a control at which defense-in-depth layer?",["Data","Perimeter","Physical","Network"],0,"Protecting the information itself sits at the data layer."],
["Which responsibility never transfers to the cloud provider in any service model?",["Protecting your accounts and identities","Patching the physical host","Maintaining the datacenter network","Replacing failed hardware"],0,"Data, devices, and identities remain the customer's responsibility in every model."]],

/* Day 2 — Concepts */
2:[
["Why does TLS combine asymmetric and symmetric encryption?",["Asymmetric safely establishes a shared key, then symmetric encrypts the bulk data quickly","Asymmetric is used for everything because it is faster","Symmetric handles key exchange and asymmetric handles the data","It uses hashing instead of both"],0,"The handshake solves key exchange; the session uses fast symmetric encryption."],
["A digital certificate primarily binds:",["A public key to a verified identity","A password to a username","A hash to a salt","A firewall rule to a port"],0,"Certificates assert that a given public key belongs to a specific identity, vouched for by a CA."],
["Integrity and non-repudiation differ because non-repudiation also proves:",["Who performed the action, so they cannot credibly deny it","That the data is encrypted","That the system is available","That the data was backed up"],0,"Integrity says the data is unchanged; non-repudiation ties the action to a specific party."],
["Governance and compliance differ because governance is:",["The organization's own internal direction and oversight","Adherence to external laws and regulations","The act of encrypting data","A type of risk assessment"],0,"Governance is internally driven; compliance answers to external requirements."],
["Single sign-on and federation are related but distinct because federation specifically:",["Establishes trust between separate organizations or identity systems","Lets a user sign in once within one organization","Encrypts credentials in transit","Requires multifactor authentication"],0,"SSO is one sign-in across apps; federation extends trust across organizational boundaries."]],

/* Day 3 — Entra ID (heavy: 25-30%) */
3:[
["What is the relationship between an Entra tenant and an Azure subscription?",["A subscription trusts exactly one tenant for identity, and a tenant can have many subscriptions","Each subscription has its own separate tenant that cannot be shared","Tenants and subscriptions are the same thing","A tenant can only ever have one subscription"],0,"Subscriptions are billing and resource containers that rely on one tenant for identity."],
["An administrative unit in Entra ID is used to:",["Scope administrative permissions to a subset of users or devices","Bill departments separately","Store encryption keys","Replace security groups entirely"],0,"Administrative units let you delegate admin rights over just one region or department."],
["A dynamic group differs from an assigned group because membership is:",["Calculated automatically from user or device attributes","Set manually by an administrator","Fixed permanently at creation","Based only on job title"],0,"Dynamic groups use attribute-based rules so membership updates itself."],
["Microsoft Entra Cloud Sync differs from Entra Connect Sync mainly because Cloud Sync:",["Uses a lightweight agent with configuration managed in the cloud","Requires a full on-premises server running SQL","Cannot sync passwords","Only works for guest accounts"],0,"Cloud Sync uses lightweight provisioning agents and is managed from the cloud."],
["A guest user invited through B2B collaboration by default has:",["Restricted directory permissions compared to a member user","Full Global Administrator rights","No access at all until made a member","The same permissions as an employee"],0,"Guests get limited default directory permissions that can be restricted further."],
["Why are workload identities considered a growing security risk?",["They often hold broad standing permissions and are less monitored than user accounts","They always require multifactor authentication","They expire after a single use","They cannot access any resources"],0,"App and service identities frequently accumulate permissions with little oversight."],
["Device identity in Entra ID matters mainly because it enables:",["Access decisions based on whether the device is known and compliant","Faster internet speeds for the device","Automatic software licensing","Physical tracking of the hardware"],0,"Registering devices lets Conditional Access evaluate device state."],
["Microsoft Entra Domain Services is best described as:",["A managed domain offering legacy protocols like LDAP and Kerberos in Azure","The same product as Entra ID","An on-premises-only directory","A replacement for Microsoft Sentinel"],0,"It provides managed domain services for workloads that still need traditional AD protocols."]],

/* Day 4 — Entra authentication */
4:[
["Number matching in Microsoft Authenticator exists to defend against:",["MFA fatigue attacks where users approve prompts reflexively","Password spraying","SQL injection","Man-in-the-middle DNS attacks"],0,"Requiring the user to type a displayed number prevents blind approval of push spam."],
["A Temporary Access Pass is used to:",["Give a time-limited passcode so a user can register a strong credential","Permanently replace a user's password","Bypass all Conditional Access policies","Grant Global Administrator rights"],0,"A TAP bridges onboarding or recovery until passwordless methods are registered."],
["Authentication strength in Conditional Access allows an administrator to:",["Require a specific class of authentication method, such as phishing-resistant MFA","Set the minimum password length","Increase the session timeout only","Disable MFA for administrators"],0,"Authentication strengths specify which method combinations satisfy a policy."],
["Password hash synchronization means:",["A hash of the on-premises password hash is synced so Entra ID can verify sign-ins","Plain-text passwords are copied to the cloud","Authentication always happens on-premises","Passwords are never stored anywhere"],0,"PHS syncs a hash of a hash, letting Entra ID authenticate users directly."],
["Pass-through authentication differs from password hash sync because it:",["Validates the password against on-premises Active Directory in real time","Stores passwords in the cloud permanently","Requires no agents at all","Only works for guest users"],0,"PTA sends the validation to an on-prem agent rather than verifying in the cloud."],
["Blocking legacy authentication protocols is important because those protocols:",["Do not support multifactor authentication and are heavily targeted","Are too slow for modern networks","Cost extra to license","Only work on mobile devices"],0,"Legacy protocols bypass MFA, making them a favorite for password attacks."],
["Per-user MFA differs from Conditional Access MFA because per-user MFA:",["Always prompts regardless of context, with no conditional logic","Evaluates device compliance and location","Requires Entra ID P2","Cannot be enabled at all"],0,"Legacy per-user MFA is unconditional; Conditional Access adds context."],
["Password writeback allows:",["Cloud password changes to be written back to on-premises Active Directory","On-premises passwords to be deleted","Users to skip MFA registration","Guests to reset employee passwords"],0,"Writeback keeps hybrid environments consistent when users reset in the cloud."]],

/* Day 5 — Conditional Access and governance */
5:[
["A Conditional Access policy is built from which three parts?",["Assignments, conditions, and access controls","Users, passwords, and licenses","Alerts, incidents, and playbooks","Labels, policies, and retention"],0,"You assign who and what it covers, set the conditions, and define the grant or session controls."],
["A session control in Conditional Access can:",["Limit sign-in frequency or restrict downloads in a browser session","Delete the user account","Change the user's job title","Encrypt the device's hard drive"],0,"Session controls shape the experience after access is granted."],
["A named location in Conditional Access is used to:",["Define trusted IP ranges or countries that policies can reference","Store the user's home address","Name the Azure region for billing","Set the device hostname"],0,"Named locations turn IP ranges and countries into reusable policy conditions."],
["A break-glass (emergency access) account should be:",["Excluded from Conditional Access policies and closely monitored","Included in every MFA policy with no exceptions","Shared openly with all administrators","Deleted after initial setup"],0,"Excluding it prevents lockout from a misconfigured policy, but it must be tightly watched."],
["A terms of use policy in Entra ID requires users to:",["Accept a document before access is granted, with acceptance recorded","Change their password monthly","Install a specific browser","Register a hardware token"],0,"Terms of use can be enforced through Conditional Access and generate an audit record."],
["A catalog in entitlement management is:",["A container that groups resources available in access packages","A list of purchased licenses","A record of past sign-ins","A retention schedule"],0,"Catalogs organize which resources can be bundled into access packages."],
["Access reviews can be performed by:",["The resource owner, the users themselves, or designated reviewers","Only Global Administrators","Only Microsoft support","Only external auditors"],0,"Reviews can be assigned to managers, group owners, self-review, or selected reviewers."],
["Risk-based Conditional Access typically responds to high user risk by:",["Requiring a secure password change or blocking access","Silently ignoring the detection","Deleting the account","Granting elevated permissions"],0,"High user risk usually triggers remediation such as a password change."]],

/* Day 7 — Azure infrastructure security (heaviest SC-900 domain) */
7:[
["A network security group includes default rules that:",["Allow virtual network traffic and deny all inbound internet traffic","Allow all inbound traffic from anywhere","Block every outbound connection","Cannot be overridden"],0,"Default rules permit intra-VNet traffic and deny inbound from the internet, and you can add higher-priority rules."],
["Azure Private Link provides:",["A private endpoint so a service is reachable over the virtual network, not the public internet","A public IP address for every resource","A VPN to on-premises only","Encryption for data at rest"],0,"Private Link keeps traffic to PaaS services on the Microsoft backbone via a private endpoint."],
["Just-in-time VM access in Defender for Cloud works by:",["Opening management ports only for an approved window and source","Leaving RDP permanently open","Disabling all inbound access forever","Encrypting the VM disk"],0,"JIT reduces exposure by closing management ports until they are explicitly requested."],
["Key Vault soft delete and purge protection exist to:",["Prevent permanent loss of keys and secrets from accidental or malicious deletion","Speed up secret retrieval","Reduce licensing costs","Automatically rotate certificates"],0,"They provide a recovery window and block premature permanent deletion."],
["The regulatory compliance dashboard in Defender for Cloud maps your configuration to:",["Standards such as ISO, PCI DSS, and NIST","Your monthly Azure invoice","The organization's staffing plan","Individual user sign-in logs"],0,"It shows how resource configuration aligns to regulatory standards."],
["A Defender for Cloud 'plan' such as Defender for Servers provides:",["Workload-specific threat detection and protection features","A billing discount","A network diagram","An identity governance workflow"],0,"Each plan adds paid workload protection for a specific resource type."],
["Defender for Cloud can assess resources in AWS and GCP by:",["Connecting those accounts as multicloud connectors","Requiring all workloads to move to Azure","Installing Azure Firewall in AWS","Exporting logs manually each month"],0,"Multicloud connectors extend posture management across other clouds."],
["Which is the best description of a Web Application Firewall's placement?",["In front of the web application, typically on Application Gateway or Front Door","On each end-user laptop","Between two on-premises domain controllers","Inside the SQL database engine"],0,"A WAF sits in front of the app to inspect inbound HTTP/S requests."],
["Azure DDoS Protection's always-on platform-level defense:",["Protects the Azure infrastructure for all customers at no additional cost","Must be purchased per virtual machine","Only applies to storage accounts","Replaces the need for a firewall"],0,"Basic infrastructure-level protection is built into the platform; paid tiers add per-resource features."],
["Encryption of Azure Storage data at rest is:",["Enabled by default using service-managed keys, with customer-managed keys optional","Not available","Only possible with a third-party product","Only applied to blobs, never files"],0,"Storage Service Encryption is on by default and supports customer-managed keys."],
["A service endpoint differs from a private endpoint because a service endpoint:",["Keeps traffic on the Azure backbone but the service still uses its public IP","Assigns a private IP inside your virtual network","Requires a VPN gateway","Only works on-premises"],0,"Private endpoints give the service an address inside your VNet; service endpoints do not."],
["Defender for Cloud recommendations are prioritized by:",["Their potential security impact, expressed through Secure Score","Alphabetical order","Resource creation date","Monthly cost"],0,"Recommendations carry weight based on the risk they address."]],

/* Day 8 — Sentinel, Defender XDR, threat intelligence (heaviest SC-900 domain) */
8:[
["Microsoft Sentinel stores its data in:",["A Log Analytics workspace","An Azure SQL database","A SharePoint site","Microsoft Purview"],0,"Sentinel is built on top of a Log Analytics workspace."],
["A Fusion analytics rule in Sentinel is designed to:",["Correlate low-fidelity signals across sources into a high-confidence multistage attack detection","Run a single keyword search","Display a dashboard","Archive old logs"],0,"Fusion uses machine learning to link weak signals into multistage attack incidents."],
["An automation rule in Sentinel differs from a playbook because the automation rule:",["Centrally triggers actions like assigning or closing incidents, and can call playbooks","Is written entirely in KQL","Only creates dashboards","Replaces data connectors"],0,"Automation rules handle incident-level logic and can invoke playbooks for complex actions."],
["Sentinel notebooks are typically used for:",["Advanced investigation and hunting using tools like Jupyter and Python","Storing user passwords","Configuring firewall rules","Assigning Microsoft 365 licenses"],0,"Notebooks support deep, repeatable investigation and data science workflows."],
["Threat intelligence in Sentinel is used to:",["Match observed activity against known malicious indicators","Generate user training material","Calculate Azure spending","Deploy virtual machines"],0,"Imported indicators of compromise enrich detections and hunting."],
["Attack surface reduction rules in Defender for Endpoint:",["Block risky behaviors such as Office apps spawning child processes","Encrypt the device's drive","Manage user licenses","Provide DDoS protection"],0,"ASR rules constrain common malware behaviors before they execute."],
["Attack simulation training is a feature of:",["Microsoft Defender for Office 365","Microsoft Sentinel","Azure Key Vault","Entra ID Protection"],0,"Defender for Office 365 includes simulated phishing campaigns and user training."],
["Defender for Identity detects threats by:",["Installing sensors on domain controllers and analyzing AD traffic and behavior","Scanning outbound email attachments","Monitoring Azure billing","Inspecting web application requests"],0,"Sensors on domain controllers give it visibility into on-prem identity attacks."],
["In Defender XDR, automated investigation and response (AIR) can:",["Investigate alerts and take remediation actions such as quarantining a file","Only send email notifications","Only generate compliance reports","Only apply sensitivity labels"],0,"AIR performs automated triage and remediation to reduce analyst workload."],
["The Microsoft Defender portal unifies which experience?",["Incidents, alerts, hunting, and settings across Defender products","Only endpoint antivirus settings","Only Azure resource deployment","Only Purview compliance policies"],0,"The Defender portal is the single pane for XDR across products."],
["Microsoft Defender Vulnerability Management prioritizes findings using:",["Risk context such as exposure and active exploitation, not just raw severity","The alphabetical order of software names","The size of the installer file","The number of users on the device"],0,"Risk-based prioritization surfaces the weaknesses most likely to be exploited in your environment."],
["User and entity behavior analytics (UEBA) in Sentinel helps by:",["Building behavioral baselines and highlighting deviations for users and entities","Blocking network traffic inline","Encrypting mailbox content","Creating access packages"],0,"UEBA surfaces anomalies relative to learned normal behavior."]],

/* Day 9 — Purview part 1 */
9:[
["An assessment template in Compliance Manager provides:",["A prebuilt set of controls mapped to a specific regulation or standard","A list of licensed users","A network topology map","An incident response playbook"],0,"Templates package the controls needed to assess against a given regulation."],
["Exact Data Match (EDM) classification is useful when you need to:",["Detect specific known values, such as your actual customer record data","Detect any number that looks like a credit card","Classify documents by writing style","Encrypt files at rest"],0,"EDM matches against a hashed upload of your real data for precision."],
["A sensitivity label policy determines:",["Which users see which labels and whether a default or mandatory label applies","The encryption algorithm used by Azure Storage","The retention period for audit logs","Which ports a firewall allows"],0,"The label defines protection; the label policy controls publication and behavior."],
["Client-side automatic labeling differs from service-side auto-labeling because client-side:",["Applies as the user works in the Office app, including recommendations","Only runs on data already stored in SharePoint","Requires no licensing","Cannot be configured by administrators"],0,"Client-side labels apply in the app; service-side policies scan content at rest and in transit."],
["A DLP policy is generally built from:",["Locations, conditions, and actions","Only a list of usernames","Only a retention period","Only an encryption key"],0,"You choose where it applies, what to detect, and what happens when it matches."],
["Endpoint DLP extends protection to:",["Actions on Windows and macOS devices such as copying to USB or printing","Only Exchange Online mailboxes","Only Azure virtual machines","Only third-party cloud apps"],0,"Endpoint DLP monitors and controls sensitive data activity on managed devices."],
["Content explorer access is typically restricted because:",["It can reveal the actual sensitive content that was detected","It consumes significant bandwidth","It only works for administrators in one region","It deletes items when opened"],0,"Viewing matched content requires elevated, separately granted permissions."],
["Microsoft's privacy principle of 'no content-based targeting' means:",["Customer content is not used to target advertising","Content is never stored","Content is always encrypted with customer keys","Content cannot be exported"],0,"Microsoft commits not to mine customer content for ad targeting."]],

/* Day 10 — Purview part 2 */
10:[
["When retention and deletion settings conflict, the general principle is:",["Retention wins over deletion, so content is kept","Deletion always wins immediately","The newest policy always wins","Nothing is applied"],0,"Retention takes precedence so content is preserved when rules conflict."],
["Disposition review allows a reviewer to:",["Decide whether to delete or keep content when its retention period ends","Recover permanently deleted items indefinitely","Change the sensitivity label of all items","Approve new user accounts"],0,"Disposition review adds a human decision point at end of retention."],
["An adaptive scope differs from a static scope because it:",["Targets locations dynamically using attribute queries","Applies to a fixed list chosen manually","Cannot be used with retention","Only applies to Teams"],0,"Adaptive scopes use queries so membership updates automatically."],
["Insider risk management policy templates typically cover scenarios such as:",["Data theft by departing users and data leaks","Firewall misconfiguration","Expired TLS certificates","Unpatched servers"],0,"Templates target insider scenarios like departing-employee data theft."],
["Information barriers are used to:",["Prevent specified groups of users from communicating with each other","Encrypt all outbound email","Block external websites","Archive Teams messages"],0,"Information barriers enforce ethical walls between groups, common in finance."],
["The typical eDiscovery workflow order is:",["Identify custodians, place holds, search and collect, review, then export","Export, review, then identify custodians","Delete, archive, then search","Label, encrypt, then delete"],0,"You scope custodians and preserve first, then collect, review, and produce."],
["Audit log search is valuable during an investigation because it can show:",["Who accessed, changed, or deleted specific content and when","The contents of every encrypted file","Future scheduled activity","The user's physical location"],0,"Audit records the who, what, and when of activity across Microsoft 365."],
["A retention label can be applied automatically based on:",["Sensitive information types, keywords, or trainable classifiers","The user's display name only","The device's IP address","The Azure region"],0,"Auto-apply retention labels use content conditions to classify items."]],

/* ======================= SECURITY+ SY0-701 ======================= */

/* Day 13 — General concepts (12%) */
13:[
["A gap analysis compares:",["The current security state against a desired target state","Two competing vendors' pricing","Last year's and this year's headcount","Inbound and outbound traffic volume"],0,"Gap analysis identifies the distance between where you are and where you need to be."],
["An infrared or pressure sensor at a facility is primarily which control type?",["Detective","Preventive","Corrective","Compensating"],0,"Sensors detect and alert on intrusion rather than physically preventing it."],
["Video surveillance combined with a visible warning sign provides which two control types?",["Detective and deterrent","Corrective and directive","Preventive and compensating","Managerial and physical"],0,"The camera detects; the sign discourages. One deployment, two types."],
["A honeypot's main defensive value is that it:",["Attracts and observes attacker behavior away from production systems","Encrypts production data","Patches vulnerable systems automatically","Blocks all inbound traffic"],0,"Honeypots divert and study attackers, generating high-confidence alerts."],
["In AAA, which component would record that a user deleted a file at 14:32?",["Accounting","Authentication","Authorization","Attestation"],0,"Accounting logs what an authenticated, authorized user actually did."],
["Access badges are typically preferred over metal keys for facilities because badges:",["Can be revoked instantly and produce an access audit trail","Are impossible to lose","Cost less to manufacture","Never need to be replaced"],0,"Revocability and logging are the security advantages over physical keys."]],

/* Day 14 — General concepts: change and crypto */
14:[
["Version control in change management supports security by:",["Providing a record of what changed and the ability to revert","Encrypting the source code","Preventing all bugs","Eliminating the need for approvals"],0,"Versioning gives traceability and a reliable rollback path."],
["A cipher suite specifies:",["The combination of algorithms used for key exchange, encryption, and integrity","The physical location of the server","The number of users allowed","The password expiration policy"],0,"A suite bundles the specific algorithms negotiated for a TLS session."],
["OCSP stapling improves on plain OCSP because the:",["Server presents a recent signed revocation status, improving privacy and speed","Client contacts the CA on every request","Certificate never expires","CRL is downloaded more often"],0,"Stapling removes the client's separate call to the CA responder."],
["A trusted platform module is best used to:",["Store keys in tamper-resistant hardware on a specific device","Manage keys for thousands of servers centrally","Filter malicious web traffic","Perform vulnerability scans"],0,"The TPM is device-bound; an HSM serves enterprise-scale key management."],
["A secure enclave provides:",["An isolated processing area protected from the rest of the system","Unlimited storage capacity","Faster network throughput","Automated patch deployment"],0,"Enclaves isolate sensitive computation and keys from the main OS."],
["Which best justifies certificate pinning for a mobile app?",["It ensures the app only trusts a specific expected certificate, resisting interception","It makes certificates last longer","It removes the need for TLS","It speeds up the handshake significantly"],0,"Pinning defends against fraudulent or compromised CA certificates."]],

/* Day 15 — Threats (22%) */
15:[
["Threat actor attributes commonly used to profile an adversary include:",["Internal versus external, resources and funding, and level of sophistication","Favorite programming language and time zone","Company size and revenue","Number of employees only"],0,"Those three attributes classify actors on the exam."],
["An unsupported system or application is a vector because:",["It no longer receives security fixes for newly discovered flaws","It always runs slower","It cannot be inventoried","It uses more bandwidth"],0,"Unsupported software accumulates permanently unpatched vulnerabilities."],
["Default credentials remain a common attack vector primarily because:",["Devices are deployed without changing factory usernames and passwords","Manufacturers never publish them","They are encrypted by default","They expire automatically"],0,"Default credentials are widely documented and frequently left in place."],
["An open service port becomes a vector when:",["A service is exposed that is unnecessary or unpatched","The port number is above 1024","The firewall logs the traffic","The service uses encryption"],0,"Unneeded exposed services broaden the attack surface."],
["Bluetooth is considered an unsecured network vector when:",["Devices remain discoverable and accept pairing without verification","It is turned off","It is used with modern pairing and encryption","It is limited to headphones"],0,"Open discovery and weak pairing allow unauthorized connections."],
["Whaling is distinguished from ordinary spear phishing because it:",["Targets senior executives or other high-value individuals","Uses SMS instead of email","Always involves malware attachments","Targets thousands of random users"],0,"Whaling is spear phishing aimed specifically at the biggest fish."],
["A watering hole attack is chosen by an attacker when:",["Direct attacks against the target fail but the target trusts a third-party site","The target has no internet access","The attacker has physical building access","The victim uses only mobile devices"],0,"Compromising a trusted, frequently visited site reaches a hardened target indirectly."],
["Impersonation and pretexting are related because pretexting:",["Supplies the fabricated story that makes the impersonation believable","Is a purely technical exploit","Only happens over email","Requires malware"],0,"The pretext is the invented context supporting the assumed identity."]],

/* Day 16 — Vulnerabilities */
16:[
["Reflected XSS differs from stored XSS because reflected XSS:",["Delivers the script in the request itself, typically via a crafted link","Is saved permanently in the application's database","Only affects the server","Requires physical access"],0,"Reflected payloads travel in the request; stored payloads persist server-side."],
["A cryptographic vulnerability arises when an application:",["Uses deprecated algorithms or manages keys poorly","Encrypts too much data","Uses TLS 1.3","Rotates keys regularly"],0,"Weak algorithms and poor key handling undermine otherwise sound encryption."],
["Side loading applications on mobile devices is risky because apps:",["Bypass the official store's vetting and code review","Cannot access the network","Always require root access","Are automatically sandboxed more tightly"],0,"Store review catches much malicious code; side loading skips that check."],
["A supply chain vulnerability involving a service provider typically means:",["A trusted provider's access to your environment is abused","Your own developers wrote insecure code","Your firewall rules are misordered","Your backups are unencrypted"],0,"MSPs and vendors hold privileged access that attackers target."],
["Legacy systems create risk primarily because:",["They may not support modern authentication, encryption, or patching","They are physically larger","They cost more to license","They use less electricity"],0,"Old platforms often can't meet current security requirements."],
["A virtualization resource reuse vulnerability could allow:",["Data from a previous workload to be exposed to a new one","The hypervisor to run faster","Automatic patching of guests","Improved network segmentation"],0,"Improperly cleared memory or storage can leak across tenants or workloads."],
["Improper input validation is the root cause of which family of attacks?",["Injection attacks such as SQLi and XSS","Physical tailgating","DDoS amplification","SIM swapping"],0,"Failing to validate and sanitize input allows attacker-controlled data to be executed."],
["Why is a misconfiguration often more dangerous than a software bug?",["It can expose systems immediately and no vendor patch will fix it","Software bugs are never exploited","Misconfigurations are always detected automatically","It only affects test environments"],0,"Configuration errors are within your control and no patch exists for them."]],

/* Day 17 — Malware and attacks */
17:[
["Modern ransomware often uses 'double extortion', which means attackers:",["Encrypt the data and also threaten to publish stolen copies","Demand payment twice from the same victim","Attack two organizations at once","Encrypt the data twice"],0,"Exfiltration plus encryption pressures victims even if they have backups."],
["The difference between spyware and adware is that spyware:",["Covertly collects information about the user","Only displays unwanted advertisements","Improves browser performance","Encrypts files for ransom"],0,"Spyware gathers data; adware pushes ads, though both are unwanted."],
["Rootkits are difficult to detect because they:",["Operate at a low level and actively hide their presence from the OS","Are always stored in plain text","Only run when the user is logged out","Require no privileges to install"],0,"Kernel-level hiding defeats tools that rely on the operating system."],
["DNS domain hijacking occurs when an attacker:",["Gains control of the domain's registrar or DNS records to redirect traffic","Floods the DNS server with queries","Encrypts DNS responses","Blocks port 53 at the firewall"],0,"Taking over registration or DNS records redirects legitimate traffic."],
["A URL redirection attack succeeds when an application:",["Accepts an untrusted destination parameter and forwards the user there","Uses HTTPS for all pages","Validates all redirect targets","Blocks outbound traffic"],0,"Unvalidated redirects send users to attacker-chosen destinations under a trusted link."],
["Privilege escalation can be described as:",["Gaining higher permissions than originally authorized","Moving data between two servers","Encrypting files with a stronger key","Reducing a user's access rights"],0,"Vertical escalation gains higher rights; horizontal accesses a peer's resources."],
["A replay attack is mitigated most directly by:",["Using timestamps, nonces, or session tokens that cannot be reused","Increasing password length","Disabling logging","Using a longer cable"],0,"Uniqueness per session prevents captured traffic from working again."],
["Which indicator most strongly suggests cryptomining malware?",["Sustained high CPU usage with outbound connections to mining pools","A single failed login","An expired certificate","A printer offline alert"],0,"Resource consumption plus mining-pool traffic is the classic pattern."]],

/* Day 18 — Mitigations */
18:[
["Isolation differs from segmentation because isolation typically:",["Completely separates a system from other network communication","Groups similar systems into subnets","Encrypts data at rest","Applies patches automatically"],0,"Segmentation partitions the network; isolation cuts a system off entirely."],
["An access control list on a router or firewall defines:",["Which traffic is permitted or denied based on specified criteria","How fast packets are forwarded","The physical cable type","The encryption algorithm"],0,"ACLs are ordered permit/deny rules applied to traffic."],
["A risk of aggressive automatic patching without testing is:",["A patch may break a production dependency and cause an outage","Patches will install too slowly","Vulnerabilities will increase","Logging will stop"],0,"Untested patches can break applications, which is why staged rollout matters."],
["Encryption mitigates which risk most directly if a laptop is stolen?",["Unauthorized disclosure of the data on the drive","Physical damage to the hardware","Loss of network connectivity","Failure of the backup job"],0,"Full-disk encryption keeps the data unreadable without the key."],
["Monitoring as a mitigation technique primarily provides:",["Timely detection so response can begin before damage spreads","Prevention of all attacks","Automatic patching","Reduced hardware costs"],0,"Monitoring shortens dwell time by surfacing activity quickly."],
["When hardening a mobile device fleet, a strong baseline includes:",["Screen lock, encryption, remote wipe, and restricted side loading","Disabling all passwords for convenience","Granting every app full permissions","Rooting each device"],0,"Those baseline controls limit exposure if a device is lost or compromised."],
["Removing unnecessary software from a system reduces risk because:",["Each installed component is potential vulnerable code that must be patched","It frees disk space for logs","It improves screen resolution","It increases network throughput"],0,"Fewer components mean a smaller attack surface and less patching burden."],
["Why should default accounts be disabled or renamed during hardening?",["Their names and passwords are publicly known and widely targeted","They consume too much memory","They cannot be audited","They expire automatically"],0,"Well-known defaults are the first thing automated attacks try."]],

/* Day 20 — Architecture (18%) */
20:[
["Which architecture consideration describes the ability to grow capacity on demand?",["Scalability","Resilience","Responsiveness","Risk transference"],0,"Scalability is the capacity to handle increased load."],
["Resilience differs from availability because resilience emphasizes:",["The ability to withstand and recover from disruption","The percentage of uptime measured","The number of concurrent users","The cost per transaction"],0,"Availability is the measure; resilience is the capacity to absorb and recover from failure."],
["A centralized architecture's main security advantage is:",["Consistent control and easier monitoring from one place","Elimination of single points of failure","Lower latency for every region","No need for access control"],0,"Centralization simplifies governance but concentrates risk."],
["Multicloud adoption complicates security mainly because:",["Each provider has different controls, tooling, and shared responsibility details","It always costs less","It removes the need for identity management","It eliminates network segmentation"],0,"Differing models and tools make consistent policy harder."],
["A key consideration before deploying an IoT fleet is:",["Whether the devices can be patched and managed over their lifetime","The color of the device casings","Whether they support 3D graphics","The vendor's marketing budget"],0,"Patch availability and manageability determine long-term risk."],
["Physical isolation (air gap) is chosen over logical segmentation when:",["The system is so critical that no network path should exist","The budget is very small","Latency must be minimized","The system needs frequent cloud updates"],0,"Air gaps are reserved for the highest-assurance environments."],
["A security benefit of software-defined networking is:",["Centralized, programmable policy enforcement across the network","Elimination of all network hardware","Automatic encryption of all data at rest","Removal of the need for authentication"],0,"SDN allows consistent policy pushed centrally, though the controller becomes critical."],
["'Ease of recovery' as an architecture consideration refers to:",["How quickly and reliably a system can be restored after failure","How simple the user interface is","How fast the network is","How cheap the licensing is"],0,"Designs differ widely in how straightforward recovery is."]],

/* Day 21 — Network design */
21:[
["A load balancer distributing requests evenly in rotation uses which algorithm?",["Round robin","Least connections","Source IP affinity","Weighted response time"],0,"Round robin cycles through servers in order."],
["Sticky sessions (source IP affinity) on a load balancer ensure:",["A client keeps reaching the same backend server","Traffic is always encrypted","Each request hits a different server","Sessions never expire"],0,"Affinity preserves session state tied to a specific server."],
["An active/passive device configuration means:",["One device handles traffic while the standby takes over on failure","Both devices share traffic equally","Neither device processes traffic","Traffic is duplicated to both permanently"],0,"Active/passive provides failover; active/active shares load."],
["A forward proxy primarily benefits an organization by:",["Filtering and logging outbound user web traffic","Accepting inbound connections for web servers","Encrypting data at rest","Issuing certificates"],0,"Forward proxies control and inspect users' outbound browsing."],
["A next-generation firewall differs from a traditional layer 4 firewall because it:",["Inspects application-layer traffic and can identify specific applications","Only filters by IP and port","Cannot log traffic","Works only on wireless networks"],0,"NGFWs add application awareness, identity, and deep inspection."],
["Which deployment allows an IPS to block traffic?",["Inline in the traffic path","Connected to a SPAN or mirror port","Attached out-of-band to a tap","Installed on a separate management VLAN only"],0,"Only an inline device can drop packets before they reach the target."],
["Tunneling with TLS versus IPsec generally differs because TLS VPNs:",["Commonly operate at the application layer and work well through browsers","Always require a dedicated hardware appliance","Cannot be used for remote access","Encrypt only the IP header"],0,"TLS VPNs are typically easier for client and browser-based remote access."],
["The main purpose of defining security zones is to:",["Group assets by trust level and control traffic between them","Assign IP addresses faster","Reduce electricity usage","Eliminate the need for authentication"],0,"Zones let you apply proportionate controls between trust boundaries."]],

/* Day 22 — Data protection and resilience */
22:[
["Human-readable data differs from non-human-readable data in that human-readable:",["Can be understood directly, like a text document or spreadsheet","Is always encrypted","Is stored only in databases","Cannot be classified"],0,"The distinction matters because classification and DLP handle each differently."],
["Data sovereignty becomes a compliance issue when:",["Data is stored in a country whose laws conflict with the organization's obligations","Data is encrypted at rest","Backups run nightly","Data is compressed"],0,"Storage location determines which legal jurisdiction applies."],
["Geographic restrictions (geofencing) on data access are used to:",["Limit where data can be accessed from, supporting sovereignty requirements","Increase bandwidth","Speed up backups","Reduce hardware costs"],0,"Restricting access by region helps enforce legal and policy boundaries."],
["Platform diversity as a resilience strategy means:",["Avoiding dependence on a single vendor or technology stack","Hiring staff with diverse backgrounds","Using one platform exclusively","Buying all hardware from one supplier"],0,"Diversity prevents one vendor flaw or outage from affecting everything."],
["Continuity of operations planning (COOP) focuses on:",["Keeping essential functions running when normal systems are unavailable","Restoring servers only","Buying cyber insurance","Conducting penetration tests"],0,"COOP addresses how the mission continues, including manual workarounds."],
["A simulation test of a disaster recovery plan is distinguished from a tabletop because it:",["Actually exercises systems and procedures rather than only discussing them","Involves fewer people","Requires no planning","Is always done annually"],0,"Simulations put the plan into practice; tabletops stay in discussion."],
["Restoration testing of backups is critical because:",["A backup that cannot be restored provides no protection","It reduces storage costs","It speeds up the backup window","It satisfies encryption requirements"],0,"Untested backups routinely fail when they are finally needed."],
["Which power protection is appropriate for extended multi-hour outages?",["A generator","A UPS alone","A surge protector","A power strip"],0,"UPS bridges seconds to minutes; generators sustain longer outages."]],

/* Day 23 — Operations (28% — heaviest Sec+ domain) */
23:[
["A secure baseline should be:",["Established, deployed, and then maintained over time","Created once and never revisited","Applied only to servers","Defined by each user individually"],0,"The exam frames baselines as establish, deploy, maintain."],
["Mobile device connection methods that expand attack surface include:",["Cellular, Wi-Fi, and Bluetooth","Only USB","Only Ethernet","Only NFC"],0,"Each radio is a potential path in and must be governed by policy."],
["A key risk of Bring Your Own Device compared to corporate-owned is:",["Limited organizational control over the device's configuration and other apps","Higher hardware cost to the company","Inability to use email","Guaranteed loss of data"],0,"BYOD trades control for convenience and cost savings."],
["Input validation should be performed:",["On the server side, even if client-side validation exists","Only in the browser","Only at the database","Never, if TLS is used"],0,"Client-side checks can be bypassed; server-side validation is authoritative."],
["Setting the Secure and HttpOnly attributes on cookies helps prevent:",["Transmission over unencrypted channels and access by client-side scripts","SQL injection","Physical theft of the device","DDoS attacks"],0,"Secure forces HTTPS; HttpOnly blocks JavaScript access, limiting XSS theft."],
["Sandboxing an application provides:",["An isolated environment limiting what the app can affect","Faster execution speed","Automatic encryption of all files","Unlimited system permissions"],0,"Sandboxes contain the impact of untrusted or compromised code."],
["Dynamic application security testing (DAST) is best described as:",["Testing a running application by sending inputs and observing behavior","Reviewing source code line by line","Checking license compliance","Scanning network ports only"],0,"DAST exercises the running app; SAST analyzes code without executing it."],
["Asset tracking and inventory matter for vulnerability management because:",["You cannot patch or protect assets you do not know exist","It reduces licensing costs only","It improves network speed","It replaces scanning"],0,"Unknown assets are unmanaged and unpatched by definition."],
["Which sanitization method is appropriate for reusing a drive internally?",["Overwriting or cryptographic erase","Physical shredding","Incineration","Degaussing an SSD"],0,"Sanitization preserves the media for reuse; destruction does not."],
["After remediating a vulnerability, the 'validation' step means:",["Rescanning or testing to confirm the fix actually worked","Filing the original report","Notifying the vendor","Purchasing a new scanner"],0,"Validation closes the loop by proving remediation was effective."]],

/* Day 24 — Operations: monitoring */
24:[
["Log aggregation provides value primarily because it:",["Centralizes logs from many sources so events can be correlated","Reduces the size of each log file","Encrypts all log data automatically","Eliminates the need for retention policies"],0,"Correlation across sources is what turns scattered logs into detection."],
["Archiving logs matters for security because:",["Investigations often uncover activity that began months earlier","It improves system performance","It reduces licensing costs","It replaces real-time alerting"],0,"Attacker dwell time frequently exceeds short retention windows."],
["Quarantine as an alert response action means:",["Isolating the affected file, message, or host to prevent further harm","Deleting all logs","Notifying the vendor","Rebuilding the network"],0,"Quarantine contains the item while investigation proceeds."],
["A content categorization web filter blocks sites based on:",["The type of content, such as gambling or malware distribution","The user's password strength","The device's MAC address","The time the site was registered"],0,"Categories let policy block classes of sites rather than individual URLs."],
["Reputation-based web filtering decides using:",["Historical trust data about a domain or IP address","The length of the URL","The server's operating system","The number of images on the page"],0,"Reputation scores reflect observed malicious behavior over time."],
["When selecting protocols during implementation, the guiding principle is:",["Choose the secure version where one exists, such as SSH over Telnet","Choose the oldest protocol for compatibility","Always use UDP for speed","Disable encryption to simplify troubleshooting"],0,"Protocol selection should default to the encrypted, modern option."],
["An email security gateway typically provides:",["Filtering of spam, phishing, and malicious attachments before delivery","Full-disk encryption on endpoints","Database access control","Wireless authentication"],0,"Gateways inspect inbound and outbound mail at the boundary."],
["Network access control (NAC) enforces security by:",["Checking device posture before granting network access","Encrypting all stored files","Scanning source code","Managing certificates"],0,"NAC gates access on compliance checks such as patch level and antivirus status."],
["XDR extends EDR by:",["Correlating detection and response across endpoints, email, identity, network, and cloud","Focusing only on a single endpoint","Replacing the need for logging","Performing only antivirus scanning"],0,"The X means extended visibility beyond the endpoint alone."],
["Reviewing a dashboard rather than raw logs is useful because dashboards:",["Summarize trends and outliers for faster situational awareness","Contain more detail than raw logs","Are legally required","Replace the need for alerts"],0,"Dashboards support quick understanding; raw logs support deep investigation."]],

/* Day 25 — Operations: IAM */
25:[
["Provisioning a user account should follow which principle from day one?",["Least privilege, granting only what the role requires","Grant administrator rights and remove later","Copy an existing user's permissions exactly","Grant access to all shared drives"],0,"Starting minimal avoids permission creep from the outset."],
["Permission creep occurs when:",["A user accumulates rights from past roles that are never removed","Passwords expire too quickly","Too many users are created","Permissions are reviewed too often"],0,"Role changes without cleanup leave excessive standing access."],
["Interoperability in federated identity matters because:",["Different systems must support common standards to exchange identity data","All systems must come from one vendor","Passwords must be identical","Each app needs its own directory"],0,"Standards like SAML and OIDC make cross-system trust possible."],
["Time-of-day restrictions are an access control that:",["Limits when an account may be used, reducing off-hours misuse","Encrypts data during business hours","Rotates passwords each morning","Assigns IP addresses dynamically"],0,"Restricting hours shrinks the window for unauthorized use."],
["'Somewhere you are' as an authentication factor is implemented using:",["Geolocation or network location data","A fingerprint reader","A hardware token","A memorized PIN"],0,"Location-based signals form the fourth commonly cited factor."],
["Current password guidance generally favors:",["Longer passphrases over frequent forced complexity changes","Mandatory 30-day expiration for all accounts","Requiring at least four special characters","Reusing one strong password everywhere"],0,"Length and uniqueness beat frequent rotation, which pushes users toward weak patterns."],
["A password manager improves security mainly by:",["Enabling unique, strong credentials for every account","Removing the need for MFA","Storing passwords in plain text for recovery","Sharing one password across the team"],0,"It solves reuse, which is the root of credential stuffing."],
["Just-in-time permissions in a PAM solution mean:",["Rights are granted only for the duration of a specific task","Permissions are permanent once approved","Access is granted without any approval","Users share one privileged account"],0,"JIT eliminates standing privilege."],
["Password vaulting in PAM provides:",["Central storage with checkout, rotation, and auditing of privileged credentials","Encryption of user documents","Automatic software patching","Network segmentation"],0,"Vaults control and record use of shared privileged credentials."],
["Federation is most appropriate when:",["Users from one organization need access to another's resources with their own credentials","All users are in one directory","Passwords must be shared","Only local accounts exist"],0,"Federation avoids creating duplicate accounts across organizations."]],

/* Day 26 — Operations: automation, IR, forensics */
26:[
["Automating resource provisioning improves security by:",["Ensuring every deployment matches a known-good, reviewed configuration","Removing the need for access control","Eliminating logging requirements","Reducing the need for backups"],0,"Consistency prevents the one-off misconfigurations that cause breaches."],
["'Workforce multiplier' as a benefit of automation means:",["A small team can cover far more work than manual effort allows","More employees must be hired","Salaries increase automatically","Training becomes unnecessary"],0,"Automation extends the reach of limited staff."],
["Technical debt from security automation refers to:",["Accumulated scripts and integrations that become costly to maintain","Unpaid software licenses","Money owed to a vendor","Outstanding vulnerability findings"],0,"Poorly maintained automation becomes fragile and expensive over time."],
["During preparation, an incident response team should:",["Define roles, build the plan, and ensure tooling and access are ready","Wait for the first incident to define roles","Only purchase insurance","Focus solely on recovery"],0,"Preparation is what makes the later phases work under pressure."],
["Why is the recovery phase distinct from eradication?",["Recovery restores normal operations and validates systems after the threat is removed","Recovery removes the malware","Recovery happens before containment","They are the same phase"],0,"Eradication removes the threat; recovery brings services back and verifies them."],
["Lessons learned should result in:",["Concrete changes to controls, processes, or training","A list of individuals to discipline","An immediate budget increase","Deletion of incident records"],0,"The phase exists to improve the program, not assign blame."],
["Threat hunting differs from incident response because hunting:",["Proactively searches for undetected threats without an initiating alert","Only begins after an alert fires","Is performed only by auditors","Replaces monitoring tools"],0,"Hunting assumes compromise and searches before detection occurs."],
["Preservation in digital forensics means:",["Protecting evidence from alteration or loss throughout the investigation","Compressing the evidence to save space","Sharing the evidence publicly","Deleting duplicate files"],0,"Preservation maintains evidentiary integrity from collection to disposition."],
["Metadata is valuable as a data source because it can reveal:",["When a file was created or modified and by whom, without reading the content","The encryption key used","The user's password","The vendor's pricing"],0,"Metadata supports timelines and attribution during investigation."],
["A packet capture is most useful when you need to:",["Examine the actual content and structure of network traffic","Summarize traffic volume over a year","Inventory installed software","Review physical access records"],0,"Full packet capture provides payload detail that flow data lacks."]],

/* Day 28 — Program management (20%) */
28:[
["An information security policy is best described as:",["A high-level statement of intent and requirements set by leadership","A step-by-step configuration guide","An optional recommendation","A vendor contract"],0,"Policies set direction; standards and procedures implement it."],
["An incident response policy differs from an incident response playbook because the policy:",["Establishes authority, scope, and requirements rather than specific steps","Lists exact commands to run","Is written by the help desk","Applies to a single incident type"],0,"Policy sets the framework; playbooks give the detailed steps."],
["An encryption standard would specify:",["Approved algorithms and key lengths the organization must use","The overall importance of confidentiality","Steps for onboarding new staff","Optional suggestions for developers"],0,"Standards are mandatory, specific technical requirements."],
["A decentralized governance structure means:",["Individual business units set and manage their own security decisions","One central body sets all policy","No policies exist","All decisions are outsourced"],0,"Decentralized models offer local agility but risk inconsistency."],
["An audit committee within a governance structure is typically responsible for:",["Overseeing controls, audits, and reporting on behalf of leadership","Writing application code","Managing the help desk queue","Purchasing hardware"],0,"Audit committees provide independent oversight of the control environment."],
["When national and local regulations conflict, an organization should generally:",["Seek legal guidance and meet the most restrictive applicable requirement","Ignore the local requirement","Ignore the national requirement","Randomly choose one"],0,"The conservative approach is to satisfy the strictest obligation, with legal counsel."],
["A data custodian's responsibility is primarily:",["Implementing and maintaining the protections the owner requires","Deciding the data's classification","Signing vendor contracts","Setting the organization's risk appetite"],0,"Custodians handle the technical safeguarding; owners set the requirements."],
["An offboarding procedure should always include:",["Revoking access and recovering organizational assets","Only collecting the badge","Only a farewell email","Only updating the org chart"],0,"Access revocation and asset recovery are the security-critical steps."],
["Monitoring and revision of governance documents is necessary because:",["Regulations, technology, and business processes change","Auditors require annual rewrites regardless of change","Employees prefer new documents","Old policies become legally void automatically"],0,"Documents must track the environment they govern."]],

/* Day 29 — Risk management */
29:[
["Continuous risk assessment differs from recurring assessment because continuous:",["Evaluates risk on an ongoing basis rather than at set intervals","Happens once per year","Is performed only after incidents","Requires no tooling"],0,"Continuous assessment uses ongoing monitoring rather than scheduled snapshots."],
["Exposure factor (EF) represents:",["The percentage of an asset's value lost in a single incident","The number of incidents per year","The total value of the asset","The cost of the control"],0,"EF is the proportional loss used to calculate SLE."],
["Annualized rate of occurrence (ARO) of 0.2 means the event is expected:",["Once every five years","Twenty times per year","Twice per year","Never"],0,"0.2 events per year equals one event every five years."],
["A risk threshold defines:",["The point at which a risk requires escalation or action","The total security budget","The number of employees needed","The encryption key length"],0,"Thresholds tie measured risk to a required response."],
["A documented risk exception typically means:",["Leadership formally accepts a risk that does not meet policy, for a defined period","The risk has been eliminated","The risk is transferred to insurance","The policy is deleted"],0,"Exceptions record accepted deviations with justification and a review date."],
["An expansionary risk appetite suggests an organization is:",["Willing to take greater risk in pursuit of growth","Unwilling to accept any risk","Focused only on compliance","Planning to shut down operations"],0,"Appetite ranges from conservative through neutral to expansionary."],
["Mean time to repair (MTTR) measures:",["The average time to restore a failed system to service","The time between failures","Acceptable data loss","Acceptable downtime"],0,"MTTR is about repair duration, not tolerance targets."],
["Requesting a vendor's independent assessment or SOC report during due diligence helps because it:",["Provides third-party validation of the vendor's controls","Guarantees the vendor will never be breached","Replaces your own contract terms","Reduces the vendor's pricing"],0,"Independent audits give evidence beyond the vendor's own claims."],
["A conflict of interest during vendor selection should be:",["Disclosed and managed to keep the decision objective","Ignored if the vendor is well known","Kept confidential from leadership","Resolved by choosing the cheapest option"],0,"Disclosure and management preserve the integrity of procurement."]],

/* Day 30 — Compliance, audits, pen testing, awareness */
30:[
["Automation in compliance monitoring is valuable because it:",["Continuously checks controls instead of relying on periodic manual review","Eliminates the need for policies","Guarantees legal immunity","Replaces external audits entirely"],0,"Automated checks catch drift between audit cycles."],
["Due care differs from due diligence because due care is:",["The ongoing responsible action taken to protect the organization","The research performed before a decision","A legal contract clause","An external audit report"],0,"Diligence investigates beforehand; care is acting responsibly over time."],
["A data inventory supports privacy compliance by:",["Documenting what personal data is held, where, and why","Encrypting all databases","Blocking external websites","Replacing retention policies"],0,"You cannot honor data subject rights without knowing what you hold."],
["An external regulatory examination differs from an independent third-party audit because the examination is:",["Conducted by a government or regulatory body with enforcement authority","Performed by the organization's own staff","Always voluntary","Focused only on financial statements"],0,"Regulators examine with legal authority; third-party auditors are engaged independently."],
["A self-assessment is most appropriately used to:",["Identify gaps internally before a formal audit","Replace all external audits","Certify regulatory compliance publicly","Satisfy a legal requirement for independence"],0,"Self-assessments prepare the organization but lack independence."],
["A physical penetration test would attempt to:",["Gain unauthorized entry to facilities through tailgating or lock bypass","Exploit a SQL injection flaw","Send phishing emails","Scan for open ports"],0,"Physical tests target facility controls rather than networks."],
["Defensive (blue team) penetration testing activities focus on:",["Detecting and responding to simulated attacks","Breaching perimeter defenses","Writing exploit code","Bypassing physical locks"],0,"Blue teams defend and detect; red teams attack."],
["Active reconnaissance carries more risk to the tester because it:",["Interacts directly with target systems and can be detected or cause disruption","Uses only public records","Requires no authorization","Happens after exploitation"],0,"Direct interaction leaves traces and can affect systems, so authorization matters."],
["Measuring the effectiveness of a security awareness program is best done by:",["Tracking metrics like phishing click rates and reporting rates over time","Counting how many slides were presented","Recording attendance only","Surveying vendor satisfaction"],0,"Behavioral metrics show whether training changed what people do."]],

/* Day 31 — Ports, logs, firewall reasoning */
31:[
["Which port does NTP use for time synchronization?",["123","69","514","161"],0,"NTP runs on UDP 123."],
["Which port does TFTP use?",["69","21","22","115"],0,"TFTP uses UDP 69 and provides no authentication or encryption."],
["Which ports does RADIUS commonly use for authentication and accounting?",["1812 and 1813","49 only","636 and 389","3389 and 445"],0,"RADIUS uses 1812 for authentication and 1813 for accounting. TACACS+ uses 49."],
["Which port does secure IMAP (IMAPS) use?",["993","143","995","110"],0,"IMAP is 143; IMAPS is 993. POP3 is 110 and POP3S is 995."],
["Which port is used for SMTP over implicit TLS?",["465","25","587","110"],0,"465 is implicit TLS; 587 is the submission port using STARTTLS."],
["Which ports are associated with legacy NetBIOS services?",["137, 138, and 139","445 only","389 and 636","1433 and 1434"],0,"NetBIOS uses 137-139; SMB over TCP uses 445."],
["Which port does LDAP use when querying the Active Directory global catalog?",["3268","389","636","88"],0,"Global catalog queries use 3268 (3269 over TLS)."],
["A firewall rule list is: 1) DENY 10.0.5.0/24 to any, 2) ALLOW 10.0.5.10 to 10.0.9.20:443. Can host 10.0.5.10 reach the server on 443?",["No, because rule 1 matches first and denies it","Yes, because rule 2 is more specific","Yes, because HTTPS is always allowed","Only outside business hours"],0,"Firewalls evaluate top-down and the first match wins, so the broad deny blocks it. The specific allow must be placed above."],
["A web server log shows thousands of requests per second from one IP to a single expensive search endpoint, and the site becomes unresponsive. This is best described as:",["An application-layer denial of service","A SQL injection attack","Directory traversal","Password spraying"],0,"Exhausting resources through legitimate-looking requests is a layer 7 DoS."],
["Authentication logs show a service account successfully authenticating to twelve different servers within two minutes, which it has never done before. This most likely indicates:",["Lateral movement using compromised credentials","A scheduled backup job","A DNS misconfiguration","A certificate expiring"],0,"Rapid authentication across many hosts is a classic lateral movement pattern."]]
};
